In [2]:
import pandas as pd

In [3]:
filtered_df = pd.read_csv("filtered_reviews.csv")

print(f"Total Reviews: {len(filtered_df):,}")
filtered_df.head()

Total Reviews: 59,996

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,46a9b775-12db-4cad-a259-83bdd6ff5b78,Muhammad Adi,https://play-lh.googleusercontent.com/a-/ALV-U...,bca gaje sinyal bagus tapi merah mulu,1,0,4.7.7,2025-12-30 19:24:57,Mohon maaf atas ketidaknyamanannya. Apabila la...,2025-12-30 19:30:44,4.7.7,BCAMOBILE_REVIEWS
1,fb449431-50de-41a5-9809-df47d670ee2a,Desak Ulantari,https://play-lh.googleusercontent.com/a-/ALV-U...,apa ini aplikasi bintang 1.. register mobile b...,1,0,NaN,2025-12-30 19:23:00,Mohon maaf atas ketidaknyamanan yang Bapak/Ibu...,2025-12-30 19:53:34,NaN,BCAMOBILE_REVIEWS
2,1390039e-cd94-4046-b864-523acc647bc9,Nuynuyaja Nuy8,https://play-lh.googleusercontent.com/a/ACg8oc...,akun nya ga bis akembali,1,0,NaN,2025-12-30 17:11:35,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2025-12-30 17:56:13,NaN,BCAMOBILE_REVIEWS
3,5fa82eb0-e111-4a8f-b397-8a6fd37d1709,Noeva Faiz,https://play-lh.googleusercontent.com/a-/ALV-U...,makin paraaaaaah setelah diupdate .aplikasi ny...,1,0,NaN,2025-12-30 16:51:09,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2025-12-30 17:07:08,NaN,BCAMOBILE_REVIEWS
4,6881a68b-b85e-4ba0-9d8b-d5a2c21a6ca4,Abcdek Kakaka,https://play-lh.googleusercontent.com/a-/ALV-U...,"indikator lampu merah terus , mana sering gitu...",1,3,4.7.7,2025-12-30 16:02:42,Mohon maaf atas ketidaknyamanannya. Apabila la...,2025-12-30 16:46:20,4.7.7,BCAMOBILE_REVIEWS

In [4]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59996 entries, 0 to 59995
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              59996 non-null  object
 1   userName              59996 non-null  object
 2   userImage             59996 non-null  object
 3   content               59996 non-null  object
 4   score                 59996 non-null  int64
 5   thumbsUpCount         59996 non-null  int64
 6   reviewCreatedVersion  46690 non-null  object
 7   at                    59996 non-null  object
 8   replyContent          59130 non-null  object
 9   repliedAt             59130 non-null  object
 10  appVersion            46690 non-null  object
 11  bank                  59996 non-null  object
dtypes: int64(2), object(10)
memory usage: 5.5+ MB

In [5]:
missing_values = (
    filtered_df
    .isnull()
    .sum()
    .reset_index()
)

missing_values.columns = ["Column", "Missing Values"]

missing_values

                  Column  Missing Values
0               reviewId               0
1               userName               0
2              userImage               0
3                content               0
4                  score               0
5          thumbsUpCount               0
6   reviewCreatedVersion           13306
7                     at               0
8           replyContent             866
9              repliedAt             866
10            appVersion           13306
11                  bank               0

In [6]:
missing_percentage = (
    filtered_df
    .isnull()
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)

missing_percentage.columns = ["Column", "Missing Percentage (%)"]

missing_percentage

                  Column  Missing Percentage (%)
0               reviewId                    0.00
1               userName                    0.00
2              userImage                    0.00
3                content                    0.00
4                  score                    0.00
5          thumbsUpCount                    0.00
6   reviewCreatedVersion                   22.18
7                     at                    0.00
8           replyContent                    1.44
9              repliedAt                    1.44
10            appVersion                   22.18
11                  bank                    0.00

In [7]:
KEEP_COLUMNS = [
    "reviewId",
    "content",
    "score",
    "at",
    "bank"
]

filtered_df = filtered_df[KEEP_COLUMNS].copy()

filtered_df.head()

,reviewId,content,score,at,bank
0,46a9b775-12db-4cad-a259-83bdd6ff5b78,bca gaje sinyal bagus tapi merah mulu,1,2025-12-30 19:24:57,BCAMOBILE_REVIEWS
1,fb449431-50de-41a5-9809-df47d670ee2a,apa ini aplikasi bintang 1.. register mobile b...,1,2025-12-30 19:23:00,BCAMOBILE_REVIEWS
2,1390039e-cd94-4046-b864-523acc647bc9,akun nya ga bis akembali,1,2025-12-30 17:11:35,BCAMOBILE_REVIEWS
3,5fa82eb0-e111-4a8f-b397-8a6fd37d1709,makin paraaaaaah setelah diupdate .aplikasi ny...,1,2025-12-30 16:51:09,BCAMOBILE_REVIEWS
4,6881a68b-b85e-4ba0-9d8b-d5a2c21a6ca4,"indikator lampu merah terus , mana sering gitu...",1,2025-12-30 16:02:42,BCAMOBILE_REVIEWS

In [8]:
duplicate_reviewid = filtered_df["reviewId"].duplicated().sum()

print(f"Duplicate Review IDs: {duplicate_reviewid:,}")

Duplicate Review IDs: 0

In [9]:
duplicate_content = filtered_df["content"].duplicated().sum()

print(f"Duplicate Review Contents: {duplicate_content:,}")

Duplicate Review Contents: 2,208

In [10]:
empty_reviews = (
    filtered_df["content"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print(f"Empty Reviews: {empty_reviews:,}")

Empty Reviews: 0

In [11]:
review_length = filtered_df["content"].astype(str).str.len()

review_length.describe()

count    59996.000000
mean       106.280419
std         90.760695
min          1.000000
25%         43.000000
50%         81.000000
75%        140.000000
max        500.000000
Name: content, dtype: float64

In [12]:
short_reviews = filtered_df[
    filtered_df["content"].astype(str).str.len() < 5
]

print(f"Short Reviews (<5 chars): {len(short_reviews):,}")

short_reviews.head(20)

Short Reviews (<5 chars): 452

,reviewId,content,score,at,bank
823,1eb85334-e3b3-4137-93d9-6ffc5cee2047,ok,3,2025-11-28 18:02:33,BCAMOBILE_REVIEWS
1234,07f1e53d-a71c-4360-8082-e2278d173227,lag,1,2025-11-10 22:26:10,BCAMOBILE_REVIEWS
1501,a4198763-e215-4da8-95b8-528714d73a52,fo,3,2025-10-22 16:19:44,BCAMOBILE_REVIEWS
2151,780d13fc-0c1e-4763-ab63-da0c2d25091a,eror,1,2025-09-29 07:35:54,BCAMOBILE_REVIEWS
2162,9e61ed09-1fdc-4c66-b7ef-8a0dc97b1a0d,eror,1,2025-09-29 07:32:32,BCAMOBILE_REVIEWS
2460,04ed17d1-f5f5-49c5-88a5-20577725ac8c,good,3,2025-09-20 20:57:34,BCAMOBILE_REVIEWS
3100,a8d82523-3b40-40e8-a366-397d091a536d,ok,1,2025-09-04 15:21:07,BCAMOBILE_REVIEWS
3495,147cb25c-23e0-4020-afde-1b0b22210b7d,🤮,1,2025-08-18 00:25:21,BCAMOBILE_REVIEWS
3580,8bddc025-9377-4329-b99b-4ceb2a4712d5,pret,1,2025-08-16 18:10:08,BCAMOBILE_REVIEWS
3639,065ebaa9-3c23-470b-85fb-1e76f6bc01a1,kuno,1,2025-08-16 08:18:55,BCAMOBILE_REVIEWS
3686,90ee669f-1297-40c9-8c84-3def59800bc9,good,1,2025-08-15 22:22:19,BCAMOBILE_REVIEWS
3873,9d618b20-05c4-41da-ac52-82d11497149a,bca😌,1,2025-08-15 09:25:18,BCAMOBILE_REVIEWS
4008,1e71e477-4d07-463c-aec4-633a3125071b,bad,1,2025-08-15 03:16:15,BCAMOBILE_REVIEWS
4235,7a24e6b5-123c-4325-8a6e-91489e60297e,iyuh,1,2025-08-14 19:14:29,BCAMOBILE_REVIEWS
4288,64b4a804-3b0b-47ea-a42f-cf1a01dde527,bad,1,2025-08-14 17:58:17,BCAMOBILE_REVIEWS
4779,aa62a5b0-3a39-49a2-ad8a-5949598a574b,baik,3,2025-07-18 22:51:51,BCAMOBILE_REVIEWS
4795,a09245c2-e5b1-4010-a236-bc14a0f3aceb,oke,3,2025-07-18 10:56:37,BCAMOBILE_REVIEWS
4807,dd3375dc-a181-4a61-8770-9ec2f8d2b430,baik,3,2025-07-17 19:47:01,BCAMOBILE_REVIEWS
5005,c41648b2-8ac1-4ca6-84e8-c1e785ea6fb4,aneh,1,2025-07-02 22:34:04,BCAMOBILE_REVIEWS
5207,4fd36478-e395-4730-8761-cfafe5ee6f0f,bad,2,2025-06-18 13:23:04,BCAMOBILE_REVIEWS

In [13]:
filtered_df["at"] = pd.to_datetime(filtered_df["at"])

filtered_df["year"] = filtered_df["at"].dt.year

filtered_df["year"].value_counts().sort_index()

year
2025    59996
Name: count, dtype: int64

In [14]:
print("Earliest Review :", filtered_df["at"].min())
print("Latest Review   :", filtered_df["at"].max())

Earliest Review : 2025-01-01 00:06:41
Latest Review   : 2025-12-30 23:59:04

In [15]:
rating_percentage = (
    filtered_df["score"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
    .to_frame("Percentage (%)")
)

rating_percentage

       Percentage (%)
score
1               68.07
2               14.90
3               17.03

final quality check

In [16]:
print("Final Dataset Shape:")
print(filtered_df.shape)

print("\nMissing Values:")
print(filtered_df.isnull().sum())

print("\nDuplicate Contents:")
print(filtered_df["content"].duplicated().sum())

Final Dataset Shape:
(59996, 6)

Missing Values:
reviewId    0
content     0
score       0
at          0
bank        0
year        0
dtype: int64

Duplicate Contents:
2208

In [18]:
filtered_df.to_csv("EDA_dataset.csv", index=False)