In [2]:
import pandas as pd

In [3]:
filtered_df = pd.read_csv("merged_reviews.csv")

print(f"Total reviews before filtering: {len(filtered_df):,}")
filtered_df.head()

Total reviews before filtering: 672,627

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,e17751da-bf2e-4a8f-a5a8-334206bb93ca,pajar,https://play-lh.googleusercontent.com/a/ACg8oc...,ribet banget ni apk sumpah dikir' verif dikit'...,1,0,NaN,2025-12-31 23:57:59,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2026-01-01 00:10:13,NaN,BCAMOBILE_REVIEWS
1,3481f1d1-a22f-445f-ae2f-ed8c2c9dca53,Jessica Slycia,https://play-lh.googleusercontent.com/a/ACg8oc...,kenapa QRis ga bisa di pakai ya?? daritadi loa...,2,0,4.7.7,2025-12-31 23:22:32,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2025-12-31 23:33:06,4.7.7,BCAMOBILE_REVIEWS
2,af69ec6d-cc97-404e-b86a-e5f5b5f1f711,Bidibetico 09,https://play-lh.googleusercontent.com/a-/ALV-U...,"aplikasi nya sampah, kenapa tiba-tiba keluar t...",1,0,4.7.7,2025-12-31 23:06:58,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2025-12-31 23:30:30,4.7.7,BCAMOBILE_REVIEWS
3,69174b3d-1234-4077-ac5a-d60aa10161e2,Pusat Data Win,https://play-lh.googleusercontent.com/a-/ALV-U...,sudah bagus dan lancar,5,0,4.7.7,2025-12-31 23:05:27,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-12-31 23:32:05,4.7.7,BCAMOBILE_REVIEWS
4,7181692a-d770-40aa-89bb-7cee4a772ad7,ade yanto,https://play-lh.googleusercontent.com/a-/ALV-U...,Sangat membantu,5,0,2.9.6,2025-12-31 22:24:00,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-12-31 23:31:26,2.9.6,BCAMOBILE_REVIEWS

2025 only filter

In [4]:
filtered_df = filtered_df[
    (filtered_df["at"] >= "2025-01-01") &
    (filtered_df["at"] <= "2025-12-31")
].copy()

print(f"Total reviews in 2025: {len(filtered_df):,}")
filtered_df.head()

Total reviews in 2025: 230,644

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
32,733993b9-c5e2-44fb-849a-0eca2ef990be,ronald koswara koswara,https://play-lh.googleusercontent.com/a/ACg8oc...,profesional dan saya puas dengan cara kerja nya.,5,0,2.9.6,2025-12-30 22:43:35,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-12-30 23:02:26,2.9.6,BCAMOBILE_REVIEWS
33,12830af5-521c-4887-ac69-1c7a34f88cfd,HANNA REM123,https://play-lh.googleusercontent.com/a/ACg8oc...,ini kenapa yaa tiap mau masuk ke apk pasti ke ...,4,0,4.7.7,2025-12-30 21:58:54,Mohon maaf apabila Bapak/Ibu mengalami untuk k...,2025-12-30 22:03:18,4.7.7,BCAMOBILE_REVIEWS
34,63e6c10b-75bb-4b8b-a698-1d74c1a0b447,Aziss Samsudin,https://play-lh.googleusercontent.com/a-/ALV-U...,bagus,5,0,4.7.7,2025-12-30 20:43:06,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-12-30 21:24:05,4.7.7,BCAMOBILE_REVIEWS
35,46a9b775-12db-4cad-a259-83bdd6ff5b78,Muhammad Adi,https://play-lh.googleusercontent.com/a-/ALV-U...,bca gaje sinyal bagus tapi merah mulu,1,0,4.7.7,2025-12-30 19:24:57,Mohon maaf atas ketidaknyamanannya. Apabila la...,2025-12-30 19:30:44,4.7.7,BCAMOBILE_REVIEWS
36,fb449431-50de-41a5-9809-df47d670ee2a,Desak Ulantari,https://play-lh.googleusercontent.com/a-/ALV-U...,apa ini aplikasi bintang 1.. register mobile b...,1,0,NaN,2025-12-30 19:23:00,Mohon maaf atas ketidaknyamanan yang Bapak/Ibu...,2025-12-30 19:53:34,NaN,BCAMOBILE_REVIEWS

Rating Distribution (Before Filtering)

In [5]:
rating_distribution = (
    filtered_df["score"]
    .value_counts()
    .sort_index()
    .rename_axis("Rating")
    .reset_index(name="Count")
)

rating_distribution

   Rating   Count
0       1   40838
1       2    8938
2       3   10220
3       4   14209
4       5  156439

rating percentage

In [6]:
rating_percentage = (
    filtered_df["score"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
    .rename_axis("Rating")
    .reset_index(name="Percentage (%)")
)

rating_percentage

   Rating  Percentage (%)
0       1           17.71
1       2            3.88
2       3            4.43
3       4            6.16
4       5           67.83

fitler rating 1 - 3

In [7]:
filtered_df = filtered_df[filtered_df["score"].isin([1, 2, 3])].copy()

print(f"Total reviews after filtering: {len(filtered_df):,}")

Total reviews after filtering: 59,996

In [8]:
summary = pd.DataFrame({
    "Dataset": ["Original", "Filtered (Rating 1-3)"],
    "Total Reviews": [
        len(filtered_df),
        len(filtered_df)
    ]
})

summary

                 Dataset  Total Reviews
0               Original          59996
1  Filtered (Rating 1-3)          59996

Rating Distribution After Filtering

In [9]:
filtered_distribution = (
    filtered_df["score"]
    .value_counts()
    .sort_index()
    .rename_axis("Rating")
    .reset_index(name="Count")
)

filtered_distribution

   Rating  Count
0       1  40838
1       2   8938
2       3  10220

In [10]:
filtered_df.to_csv("filtered_reviews.csv", index=False)