In [2]:
import pandas as pd

In [3]:
merged_df = pd.read_csv("data/merged_reviews.csv")

print(f"Total reviews before filtering: {len(merged_df):,}")
merged_df.head()

Total reviews before filtering: 672,627

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,e17751da-bf2e-4a8f-a5a8-334206bb93ca,pajar,https://play-lh.googleusercontent.com/a/ACg8oc...,ribet banget ni apk sumpah dikir' verif dikit'...,1,0,NaN,2025-12-31 23:57:59,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2026-01-01 00:10:13,NaN,BCAMOBILE_REVIEWS
1,3481f1d1-a22f-445f-ae2f-ed8c2c9dca53,Jessica Slycia,https://play-lh.googleusercontent.com/a/ACg8oc...,kenapa QRis ga bisa di pakai ya?? daritadi loa...,2,0,4.7.7,2025-12-31 23:22:32,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2025-12-31 23:33:06,4.7.7,BCAMOBILE_REVIEWS
2,af69ec6d-cc97-404e-b86a-e5f5b5f1f711,Bidibetico 09,https://play-lh.googleusercontent.com/a-/ALV-U...,"aplikasi nya sampah, kenapa tiba-tiba keluar t...",1,0,4.7.7,2025-12-31 23:06:58,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2025-12-31 23:30:30,4.7.7,BCAMOBILE_REVIEWS
3,69174b3d-1234-4077-ac5a-d60aa10161e2,Pusat Data Win,https://play-lh.googleusercontent.com/a-/ALV-U...,sudah bagus dan lancar,5,0,4.7.7,2025-12-31 23:05:27,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-12-31 23:32:05,4.7.7,BCAMOBILE_REVIEWS
4,7181692a-d770-40aa-89bb-7cee4a772ad7,ade yanto,https://play-lh.googleusercontent.com/a-/ALV-U...,Sangat membantu,5,0,2.9.6,2025-12-31 22:24:00,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-12-31 23:31:26,2.9.6,BCAMOBILE_REVIEWS

Rating Distribution (Before Filtering)

In [4]:
rating_distribution = (
    merged_df["score"]
    .value_counts()
    .sort_index()
    .rename_axis("Rating")
    .reset_index(name="Count")
)

rating_distribution

   Rating   Count
0       1  131838
1       2   30789
2       3   31382
3       4   40803
4       5  437815

rating percentage

In [5]:
rating_percentage = (
    merged_df["score"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
    .rename_axis("Rating")
    .reset_index(name="Percentage (%)")
)

rating_percentage

   Rating  Percentage (%)
0       1           19.60
1       2            4.58
2       3            4.67
3       4            6.07
4       5           65.09

fitler rating 1 - 3

In [6]:
filtered_df = merged_df[merged_df["score"].isin([1, 2, 3])].copy()

print(f"Total reviews after filtering: {len(filtered_df):,}")

Total reviews after filtering: 194,009

In [7]:
summary = pd.DataFrame({
    "Dataset": ["Original", "Filtered (Rating 1-3)"],
    "Total Reviews": [
        len(merged_df),
        len(filtered_df)
    ]
})

summary

                 Dataset  Total Reviews
0               Original         672627
1  Filtered (Rating 1-3)         194009

Rating Distribution After Filtering

In [8]:
filtered_distribution = (
    filtered_df["score"]
    .value_counts()
    .sort_index()
    .rename_axis("Rating")
    .reset_index(name="Count")
)

filtered_distribution

   Rating   Count
0       1  131838
1       2   30789
2       3   31382

In [9]:
filtered_df.to_csv("data/filtered_reviews.csv", index=False)