In [2]:
import pandas as pd

In [3]:
filtered_df = pd.read_csv("data/filtered_reviews.csv")

print(f"Total Reviews: {len(filtered_df):,}")
filtered_df.head()

Total Reviews: 194,009

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,e17751da-bf2e-4a8f-a5a8-334206bb93ca,pajar,https://play-lh.googleusercontent.com/a/ACg8oc...,ribet banget ni apk sumpah dikir' verif dikit'...,1,0,NaN,2025-12-31 23:57:59,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2026-01-01 00:10:13,NaN,BCAMOBILE_REVIEWS
1,3481f1d1-a22f-445f-ae2f-ed8c2c9dca53,Jessica Slycia,https://play-lh.googleusercontent.com/a/ACg8oc...,kenapa QRis ga bisa di pakai ya?? daritadi loa...,2,0,4.7.7,2025-12-31 23:22:32,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2025-12-31 23:33:06,4.7.7,BCAMOBILE_REVIEWS
2,af69ec6d-cc97-404e-b86a-e5f5b5f1f711,Bidibetico 09,https://play-lh.googleusercontent.com/a-/ALV-U...,"aplikasi nya sampah, kenapa tiba-tiba keluar t...",1,0,4.7.7,2025-12-31 23:06:58,Mohon maaf atas ketidaknyamanan Bapak/Ibu. Moh...,2025-12-31 23:30:30,4.7.7,BCAMOBILE_REVIEWS
3,32d28ac6-c538-4749-969f-8af060915d96,ABDUL Kodir,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus,3,0,4.7.7,2025-12-31 21:47:45,Terima kasih atas ulasannya. Semoga aplikasi B...,2025-12-31 22:06:01,4.7.7,BCAMOBILE_REVIEWS
4,f99259b7-0d45-4422-b667-6c4fd521638b,Prr G,https://play-lh.googleusercontent.com/a/ACg8oc...,tidak ada solusi ketika ada kendala di persuli...,1,0,2.9.6,2025-12-31 21:18:21,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2025-12-31 22:04:38,2.9.6,BCAMOBILE_REVIEWS

In [4]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194009 entries, 0 to 194008
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   reviewId              194009 non-null  object
 1   userName              194009 non-null  object
 2   userImage             194009 non-null  object
 3   content               194009 non-null  object
 4   score                 194009 non-null  int64
 5   thumbsUpCount         194009 non-null  int64
 6   reviewCreatedVersion  152349 non-null  object
 7   at                    194009 non-null  object
 8   replyContent          192256 non-null  object
 9   repliedAt             192256 non-null  object
 10  appVersion            152349 non-null  object
 11  bank                  194009 non-null  object
dtypes: int64(2), object(10)
memory usage: 17.8+ MB

In [5]:
missing_values = (
    filtered_df
    .isnull()
    .sum()
    .reset_index()
)

missing_values.columns = ["Column", "Missing Values"]

missing_values

                  Column  Missing Values
0               reviewId               0
1               userName               0
2              userImage               0
3                content               0
4                  score               0
5          thumbsUpCount               0
6   reviewCreatedVersion           41660
7                     at               0
8           replyContent            1753
9              repliedAt            1753
10            appVersion           41660
11                  bank               0

In [6]:
missing_percentage = (
    filtered_df
    .isnull()
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)

missing_percentage.columns = ["Column", "Missing Percentage (%)"]

missing_percentage

                  Column  Missing Percentage (%)
0               reviewId                    0.00
1               userName                    0.00
2              userImage                    0.00
3                content                    0.00
4                  score                    0.00
5          thumbsUpCount                    0.00
6   reviewCreatedVersion                   21.47
7                     at                    0.00
8           replyContent                    0.90
9              repliedAt                    0.90
10            appVersion                   21.47
11                  bank                    0.00

In [7]:
KEEP_COLUMNS = [
    "reviewId",
    "content",
    "score",
    "at"
]

filtered_df = filtered_df[KEEP_COLUMNS].copy()

filtered_df.head()

,reviewId,content,score,at
0,e17751da-bf2e-4a8f-a5a8-334206bb93ca,ribet banget ni apk sumpah dikir' verif dikit'...,1,2025-12-31 23:57:59
1,3481f1d1-a22f-445f-ae2f-ed8c2c9dca53,kenapa QRis ga bisa di pakai ya?? daritadi loa...,2,2025-12-31 23:22:32
2,af69ec6d-cc97-404e-b86a-e5f5b5f1f711,"aplikasi nya sampah, kenapa tiba-tiba keluar t...",1,2025-12-31 23:06:58
3,32d28ac6-c538-4749-969f-8af060915d96,bagus,3,2025-12-31 21:47:45
4,f99259b7-0d45-4422-b667-6c4fd521638b,tidak ada solusi ketika ada kendala di persuli...,1,2025-12-31 21:18:21

In [8]:
duplicate_reviewid = filtered_df["reviewId"].duplicated().sum()

print(f"Duplicate Review IDs: {duplicate_reviewid:,}")

Duplicate Review IDs: 0

In [9]:
duplicate_content = filtered_df["content"].duplicated().sum()

print(f"Duplicate Review Contents: {duplicate_content:,}")

Duplicate Review Contents: 7,717

In [10]:
empty_reviews = (
    filtered_df["content"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print(f"Empty Reviews: {empty_reviews:,}")

Empty Reviews: 0

In [11]:
review_length = filtered_df["content"].astype(str).str.len()

review_length.describe()

count    194009.000000
mean        103.561773
std          87.722204
min           1.000000
25%          43.000000
50%          79.000000
75%         136.000000
max         551.000000
Name: content, dtype: float64

In [12]:
short_reviews = filtered_df[
    filtered_df["content"].astype(str).str.len() < 5
]

print(f"Short Reviews (<5 chars): {len(short_reviews):,}")

short_reviews.head(20)

Short Reviews (<5 chars): 1,380

                                  reviewId content  score                   at
839   1eb85334-e3b3-4137-93d9-6ffc5cee2047      ok      3  2025-11-28 18:02:33
1250  07f1e53d-a71c-4360-8082-e2278d173227     lag      1  2025-11-10 22:26:10
1517  a4198763-e215-4da8-95b8-528714d73a52      fo      3  2025-10-22 16:19:44
2167  780d13fc-0c1e-4763-ab63-da0c2d25091a    eror      1  2025-09-29 07:35:54
2178  9e61ed09-1fdc-4c66-b7ef-8a0dc97b1a0d    eror      1  2025-09-29 07:32:32
2476  04ed17d1-f5f5-49c5-88a5-20577725ac8c    good      3  2025-09-20 20:57:34
3116  a8d82523-3b40-40e8-a366-397d091a536d      ok      1  2025-09-04 15:21:07
3511  147cb25c-23e0-4020-afde-1b0b22210b7d       🤮      1  2025-08-18 00:25:21
3596  8bddc025-9377-4329-b99b-4ceb2a4712d5    pret      1  2025-08-16 18:10:08
3655  065ebaa9-3c23-470b-85fb-1e76f6bc01a1    kuno      1  2025-08-16 08:18:55
3702  90ee669f-1297-40c9-8c84-3def59800bc9    good      1  2025-08-15 22:22:19
3889  9d618b20-05c4-41da-ac52-82d11497149a    bca😌      1  2025-08-15 09:25:18
4024  1e71e477-4d07-463c-aec4-633a3125071b     bad      1  2025-08-15 03:16:15
4251  7a24e6b5-123c-4325-8a6e-91489e60297e    iyuh      1  2025-08-14 19:14:29
4304  64b4a804-3b0b-47ea-a42f-cf1a01dde527     bad      1  2025-08-14 17:58:17
4795  aa62a5b0-3a39-49a2-ad8a-5949598a574b    baik      3  2025-07-18 22:51:51
4811  a09245c2-e5b1-4010-a236-bc14a0f3aceb     oke      3  2025-07-18 10:56:37
4823  dd3375dc-a181-4a61-8770-9ec2f8d2b430    baik      3  2025-07-17 19:47:01
5021  c41648b2-8ac1-4ca6-84e8-c1e785ea6fb4    aneh      1  2025-07-02 22:34:04
5223  4fd36478-e395-4730-8761-cfafe5ee6f0f     bad      2  2025-06-18 13:23:04

In [14]:
filtered_df["at"] = pd.to_datetime(filtered_df["at"])

filtered_df["year"] = filtered_df["at"].dt.year

filtered_df["year"].value_counts().sort_index()

year
2023    74538
2024    59301
2025    60170
Name: count, dtype: int64

In [15]:
print("Earliest Review :", filtered_df["at"].min())
print("Latest Review   :", filtered_df["at"].max())

Earliest Review : 2023-01-01 00:14:47
Latest Review   : 2025-12-31 23:57:59

In [16]:
rating_percentage = (
    filtered_df["score"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
    .to_frame("Percentage (%)")
)

rating_percentage

       Percentage (%)
score
1               67.95
2               15.87
3               16.18

final quality check

In [13]:
print("Final Dataset Shape:")
print(filtered_df.shape)

print("\nMissing Values:")
print(filtered_df.isnull().sum())

print("\nDuplicate Contents:")
print(filtered_df["content"].duplicated().sum())

Final Dataset Shape:
(194009, 4)

Missing Values:
reviewId    0
content     0
score       0
at          0
dtype: int64

Duplicate Contents:
7717

In [17]:
filtered_df.to_csv("data/EDA_dataset.csv", index=False)