In [1]:
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

c:\Users\PC\anaconda3\envs\skripsi\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv("data/processed/clean_data.csv")

print(df.shape)
df.head()

(12000, 3)

                                          clean_text  score               bank
0           dikit verivikasi ribet mohon di perbaiki      1  BCAMobile_reviews
1     sangat terbantu sexali dg adanya m bangking in      1  BCAMobile_reviews
2       kenapa sy tidak bisa mendownlod aplikasi bca      1  BCAMobile_reviews
3  sangat kecewa saya melakukan transfer keterang...      1  BCAMobile_reviews
4                            update an baru ada bugs      1  BCAMobile_reviews

In [3]:
texts = df["clean_text"].astype(str).tolist()

# IndoBERT

In [4]:
model = SentenceTransformer(
  "indobenchmark/indobert-base-p1",
  device="cuda" # using rtx 3060
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 14214.83it/s]

In [5]:
embeddings = model.encode(texts,batch_size=32,show_progress_bar=True)

Batches:   0%|          | 0/375 [00:00<?, ?it/s]

Batches: 100%|██████████| 375/375 [00:12<00:00, 29.53it/s]

In [6]:
# sanity check
sim = cosine_similarity([embeddings[0]], embeddings[:10])

print(sim)

# expected result
# nilai mendekati 1 = mirip
# lebih kecil = beda

[[0.9999999  0.47826347 0.5376282  0.5520282  0.64250004 0.501776
  0.5075089  0.44884416 0.5895494  0.5600138 ]]

| Nilai similarity | Arti                |
| ---------------- | ------------------- |
| ~0.9             | hampir identik      |
| 0.6 – 0.8        | mirip               |
| 0.4 – 0.6        | agak mirip (normal) |
| <0.3             | beda                |

In [7]:
print(texts[0])
print(texts[1])

dikit verivikasi ribet mohon di perbaiki
sangat terbantu sexali dg adanya m bangking in

# BERTopic

In [8]:
from bertopic import BERTopic

In [9]:
topic_model = BERTopic()

topics, probs = topic_model.fit_transform(texts, embeddings)

In [10]:
df["topic"] = topics
df.head()

,clean_text,score,bank,topic
0,dikit verivikasi ribet mohon di perbaiki,1,BCAMobile_reviews,0
1,sangat terbantu sexali dg adanya m bangking in,1,BCAMobile_reviews,0
2,kenapa sy tidak bisa mendownlod aplikasi bca,1,BCAMobile_reviews,0
3,sangat kecewa saya melakukan transfer keterang...,1,BCAMobile_reviews,0
4,update an baru ada bugs,1,BCAMobile_reviews,0

In [11]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,43,-1_transaksi_brimo_tidak_bisa,"[transaksi, brimo, tidak, bisa, sangat, kecewa...",[ini kenapa tidak bisa buka pake sidik jari ya...
1,0,11945,0_di_bisa_saya_tidak,"[di, bisa, saya, tidak, aplikasi, ini, nya, ad...","[ini kenapa jadi tidak bisa di buka lagi sih, ..."
2,1,12,1_biometrik_login_force_close,"[biometrik, login, force, close, jari, sidik, ...",[mengaktifkan login biometrik keluar sendiri d...

# Evaluating

In [12]:
df["topic"].value_counts().head()

topic
 0    11945
-1       43
 1       12
Name: count, dtype: int64

too many "-1" meaning too many noises => clustering failed

# Tuning

In [13]:
from hdbscan import HDBSCAN

hdbscan_model = HDBSCAN(
  min_cluster_size=50,   # default terlalu kecil/besar tergantung kasus
  min_samples=5,         # lebih longgar
  prediction_data=True
)

In [14]:
topic_model = BERTopic(
  hdbscan_model=hdbscan_model
)

topics, probs = topic_model.fit_transform(texts, embeddings)

In [15]:
df["topic"] = topics
df["topic"].value_counts().head(10)

topic
-1    7038
 0     720
 1     708
 2     476
 3     345
 4     278
 5     265
 6     233
 7     190
 8     179
Name: count, dtype: int64

In [16]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,7038,-1_bisa_di_ini_mau,"[bisa, di, ini, mau, nya, aplikasi, saya, kena...",[ini kenapa ya kok tidak bisa masuk ke livinny...
1,0,720,0_saldo_saya_tidak_ada,"[saldo, saya, tidak, ada, tapi, sudah, uang, d...",[kemarin saya melakukan transanksi tranfer ke ...
2,1,708,1_update_mulu_sangat_gangguan,"[update, mulu, sangat, gangguan, membantu, mud...","[tiap bulan update mulu, update mulu ribet, up..."
3,2,476,2_tolong_perbaiki_mohon_di,"[tolong, perbaiki, mohon, di, aplikasi, bisa, ...",[setelah update malah tidak dapat di buka tolo...
4,3,345,3_sy_yg_gk_tp,"[sy, yg, gk, tp, klo, tdk, bs, lg, di, udh]",[knp hrs ada wondr klo bni mobile banking msh ...
5,4,278,4_tunai_tarik_fitur_mobile,"[tunai, tarik, fitur, mobile, bni, tanpa, seto...","[belum ada fitur tarik tunai, fitur mobile tun..."
6,5,265,5_tidak_bisa_buka_di,"[tidak, bisa, buka, di, aplikasi, dibuka, upda...","[sering tidak bisa di buka, aplikasi tidak bis..."
7,6,233,6_jaringan_padahal_sinyal_bagus,"[jaringan, padahal, sinyal, bagus, wifi, inter...",[selalu gangguan jaringan padahal jaringan bag...
8,7,190,7_kode_benar_otp_padahal,"[kode, benar, otp, padahal, login, password, m...",[aku tidak bisa buka aplikasinya kenapa yah pa...
9,8,179,8_wajah_verifikasi_gagal_susah,"[wajah, verifikasi, gagal, susah, ribet, veriv...","[gagal verifikasi wajah mulu, verifikasi wajah..."
10,9,147,9_aja_makin_ribet_pake,"[aja, makin, ribet, pake, mau, harus, udah, la...",[masuk ulang mbanking sekarang ribet banget ba...
11,10,126,10_sering_gangguan_terlalu_banyak,"[sering, gangguan, terlalu, banyak, error, ero...","[terlalu sering error sekarang, sering ganggua..."
12,11,119,11_saya_tidak_mohon_untuk,"[saya, tidak, mohon, untuk, sudah, bisa, dan, ...",[kenapa ya aplikasi bisa dibuka hanya pas meng...
13,12,118,12_kenapa_dibuka_bisa_tidak,"[kenapa, dibuka, bisa, tidak, aplikasi, di, bu...","[kenapa aplikasi livin saya tidak bisa dibuka,..."
14,13,114,13_update_malah_di_setelah,"[update, malah, di, setelah, gak, bisa, dibuka...","[setelah di update ko malah gak bisa dibuka, d..."
15,14,113,14_bisa_kenapa_buka_dibuka,"[bisa, kenapa, buka, dibuka, gak, kok, ya, knp...","[ini kenapa livin gak bisa dibuka ya, kenapa g..."
16,15,104,15_kenapa_kok_bisa_transfer,"[kenapa, kok, bisa, transfer, ya, gak, transak...",[kenapa gak bisa transfer ke dana kok gagal mu...
17,16,88,16_merah_indikator_lampu_hijau,"[merah, indikator, lampu, hijau, indikatornya,...","[indikator lampu sering merah, kenapa ya lampu..."
18,17,81,17_verifikasi_gagal_wajah_kamera,"[verifikasi, gagal, wajah, kamera, foto, sudah...",[aplikasi gajelas susah untuk verifikasi ktp s...
19,18,80,18_bank_lebih_aja_bca,"[bank, lebih, aja, bca, gak, lagi, di, udah, k...",[verifikasi wajah sma ktp segala mana susah bg...
20,19,77,19_kenapa_saya_bisa_tidak,"[kenapa, saya, bisa, tidak, akun, login, brimo...","[kenapa tidak bisa login, kenapa saya tidak bi..."
21,20,72,20_update_malah_close_force,"[update, malah, close, force, setelah, bukanny...",[habis update malah sering force close update ...
22,21,59,21_jam_malam_maintenance_pagi,"[jam, malam, maintenance, pagi, pemeliharaan, ...",[lelet setiap dibuka kalo lagi urgent jam jam ...
23,22,57,22_cara_gimana_referal_kode,"[cara, gimana, referal, kode, gmna, ganti, hp,...","[cara buka akun yg ke blokir gimana ya, cara g..."
24,23,57,23_uninstall_instal_uninstal_udah,"[uninstall, instal, uninstal, udah, bisa, di, ...",[setiap mau login selalu muncul tulisan layana...
25,24,53,24_bank_cs_mulu_jelas,"[bank, cs, mulu, jelas, duit, tiap, banget, mo...",[bca emang agak nggak jelas gk kaya bank lain ...
26,25,53,25_makin_kesini_semakin_jelek,"[makin, kesini, semakin, jelek, sini, parah, l...",[makin kesini makin jelek aplikasi susah untuk...
27,26,50,26_susah_daftar_ribet_sulit,"[susah, daftar, ribet, sulit, mahal, registras...","[susah verifikasi, susah verifikasi nya, susah..."

still shit , adding UMAP

# UMAP Combination

In [26]:
from umap import UMAP

umap_model = UMAP(
  n_neighbors=5,
  n_components=5,
  min_dist=0.0,
  metric='cosine'
)

In [27]:
topic_model = BERTopic(
  umap_model=umap_model,
  hdbscan_model=hdbscan_model
)

topics, probs = topic_model.fit_transform(texts, embeddings)

In [28]:
df["topic"] = topics
df["topic"].value_counts().head(10)

topic
-1    5703
 0     880
 1     232
 2     218
 3     203
 4     186
 5     172
 6     168
 7     168
 8     166
Name: count, dtype: int64

In [29]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5703,-1_bisa_di_mau_ini,"[bisa, di, mau, ini, aplikasi, nya, saya, gak,...",[awal pake apk ini lancar dan stabil tapi di b...
1,0,880,0_saldo_saya_ada_tapi,"[saldo, saya, ada, tapi, tidak, sudah, uang, d...",[punya pengalaman yg sangat buruk dengan bank ...
2,1,232,1_potongan_rb_bank_biaya,"[potongan, rb, bank, biaya, aja, bca, ribu, sa...",[apaan nih brimo selalu ada potongan hampir ti...
3,2,218,2_update_lemot_sering_malah,"[update, lemot, sering, malah, terus, banget, ...","[sering update tp malah tambah lemot, update t..."
4,3,203,3_bbm_buruk_av_mm,"[bbm, buruk, av, mm, www, jelek, see, nb, oo, ...",[tong iy purwantiningsih o n an do ra san ni n...
5,4,186,4_tunai_tarik_setor_tanpa,"[tunai, tarik, setor, tanpa, kartu, mobile, fi...",[fitur mobile tunai belum tersedia kayanya sep...
6,5,172,5_wajah_verifikasi_gagal_susah,"[wajah, verifikasi, gagal, susah, ampun, aja, ...","[tidak bisa verifikasi wajah gagal mulu, gagal..."
7,6,168,6_tidak_bisa_aplikasi_setelah,"[tidak, bisa, aplikasi, setelah, brimo, dibuka...",[tiba aplikasi tidak bisa dibuka setelah di in...
8,7,168,7_sy_tdk_bs_tp,"[sy, tdk, bs, tp, yg, bni, jg, hrs, klo, jd]",[lampu indikator merah selm hari pdhl internet...
9,8,166,8_udah_verifikasi_wajah_ribet,"[udah, verifikasi, wajah, ribet, banget, gak, ...",[mau daftar susah banget verifikasi muka gagal...
10,9,159,9_aplikasi_update_tidak_close,"[aplikasi, update, tidak, close, saya, setelah...",[setelah di update mengapa tidak bisa di gunak...
11,10,156,10_buka_bisa_di_dibuka,"[buka, bisa, di, dibuka, ga, tidak, tiba, susa...","[gak bisa di buka ini, sering tidak bisa di bu..."
12,11,155,11_kenapa_dibuka_bisa_aplikasi,"[kenapa, dibuka, bisa, aplikasi, tidak, buka, ...","[aplikasinya kenapa tidak bisa dibuka, kenapa ..."
13,12,151,12_force_close_update_kenapa,"[force, close, update, kenapa, gangguan, sih, ...","[bagus setelah update selalu force close, seka..."
14,13,135,13_jaringan_bagus_sinyal_padahal,"[jaringan, bagus, sinyal, padahal, koneksi, wi...",[aplikasi nya ga bisa di buka padahal sinyal b...
15,14,129,14_sangat_membantu_mudah_bagus,"[sangat, membantu, mudah, bagus, memudahkan, m...","[sangat membantu livin mandiri, aplikasi yg sa..."
16,15,125,15_kenapa_saya_tidak_bisa,"[kenapa, saya, tidak, bisa, akun, login, brimo...","[kenapa tidak bisa login, kenapa saya tidak bi..."
17,16,113,16_mulu_dikit_update_keseringan,"[mulu, dikit, update, keseringan, jangan, eror...","[eror mulu, keseringan update mulu, dikit diki..."
18,17,109,17_kenapa_dibuka_bisa_ya,"[kenapa, dibuka, bisa, ya, kok, gak, ko, buka,...","[ini kenapa livin gak bisa dibuka ya, kenapa g..."
19,18,109,18_benar_password_username_padahal,"[benar, password, username, padahal, pasword, ...",[mengapa akun brimo tidak bisa login padahal u...
20,19,108,19_knpa_knp_gk_bisa,"[knpa, knp, gk, bisa, bs, buka, livin, sya, ya...",[knpa saya pindah brimo lain hp gk bisa d buka...
21,20,108,20_klo_yg_maintenance_jam,"[klo, yg, maintenance, jam, kalo, malam, aja, ...",[lebih baik aplikasi yg lama daripada ini lemo...
22,21,105,21_tolong_perbaiki_diperbaiki_mohon,"[tolong, perbaiki, diperbaiki, mohon, sering, ...","[tolong di perbaiki sering gangguan, sering er..."
23,22,103,22_cara_gimana_gmna_lupa,"[cara, gimana, gmna, lupa, kartu, nya, apakah,...","[cara ganti nomor hp gmna, cara buka akun yg k..."
24,23,102,23_malah_update_di_setelah,"[malah, update, di, setelah, dibuka, buka, gak...","[setelah di update ko malah gak bisa dibuka, d..."
25,24,102,24_lama_sering_eror_bagus,"[lama, sering, eror, bagus, yg, aplikasi, bagu...",[eror mulu loading masuknya lama padahal hp ba...
26,25,102,25_jaringan_perbaiki_tolong_banget,"[jaringan, perbaiki, tolong, banget, bagus, in...",[setelah diupdate ke versi terbaru kok malah j...
27,26,99,26_saya_kartu_tidak_akun,"[saya, kartu, tidak, akun, lupa, login, sudah,...",[kenapa setelah di perbaharui tidak mau masuk ...
28,27,99,27_pinjaman_wallet_ada_kenapa,"[pinjaman, wallet, ada, kenapa, up, tidak, dan...",[kenapa fitur pinjaman di living saya tidak ad...
29,28,96,28_aja_cs_bank_bikin,"[aja, cs, bank, bikin, kalo, duit, gak, ga, bu...",[apk sampahkalo nggak bisa bikin sistem deteks...
30,29,91,29_verifikasi_terus_mau_padahal,"[verifikasi, terus, mau, padahal, masuk, hp, l...",[kenapa saya mau login ulang kok ga bisa ya pa...
31,30,91,30_mlh_lg_gk_sllu,"[mlh, lg, gk, sllu, pke, aj, bs, udh, sndiri, ...",[kpda admin tlg d perbaiki lg systim nyasy ga ...
32,31,84,31_susah_daftar_flazz_sulit,"[susah, daftar, flazz, sulit, ribet, top, up, ...","[susah verifikasi, susah login daftar ulang, s..."
33,32,83,32_update_makin_ngga_mau,"[update, makin, ngga, mau, lagi, loading, teru...",[ini aplikasi kok makin di update makin jelek ...
34,33,83,33_bgt_susah_mau_mulu,"[bgt, susah, mau, mulu, terus, masa, ga, masuk...","[apk ga jelas susah kali mau login, buruk bgt ..."
35,34,82,34_sering_gangguan_terlalu_error,"[sering, gangguan, terlalu, error, lemot, trou...","[sekarang sering sekali gangguan, terlalu seri..."
36,35,81,35_tolong_perbaiki_dong_di,"[tolong, perbaiki, dong, di, mohon, update, ap...",[akun udah jadi tapi ga bisa login tolong di p...
37,36,81,36_tiba_kenapa_buka_keluar,"[tiba, kenapa, buka, keluar, brimo, aplikasi, ...",[kenapa ya akhir ini aplikasi brimo saya serin...
38,37,81,37_merah_indikator_lampu_hijau,"[merah, indikator, lampu, hijau, indikatornya,...","[indikator lampu sering merah, kenapa ya lampu..."
39,38,75,38_lama_susah_banget_gangguan,"[lama, susah, banget, gangguan, bikin, aplikas...","[sering gangguan mau transaksi susah, buka apl..."
40,39,68,39_makin_kesini_semakin_lemot,"[makin, kesini, semakin, lemot, parah, sini, j...",[makin kesini makin jelek aplikasi susah untuk...
41,40,68,40_sendiri_keluar_kenapa_login,"[sendiri, keluar, kenapa, login, gimana, terus...",[udah update mau login malah gak bisa gimana i...
42,41,63,41_mohon_saya_tidak_dan,"[mohon, saya, tidak, dan, untuk, sangat, bisa,...",[maaf sebelum nya ini saya dari tadi malam sam...
43,42,62,42_verifikasi_gagal_foto_ktp,"[verifikasi, gagal, foto, ktp, wajah, daftar, ...",[susah buat verifikasi foto di hp baru data id...
44,43,62,43_terlalu_sering_update_minta,"[terlalu, sering, update, minta, tepat, mainte...","[terlalu banyak update, perbaikan yang terlalu..."
45,44,59,44_sering_saat_error_transaksi,"[sering, saat, error, transaksi, eror, aplikas...","[aplikasi sering error perbaiki lagi, apk nya ..."
46,45,59,45_pake_ribet_harus_ktp,"[pake, ribet, harus, ktp, daftar, mau, kartu, ...",[ribet daftar nya masa mau daftar bank aja hrs...
47,46,56,46_kenapa_transfer_saldo_antar,"[kenapa, transfer, saldo, antar, cabang, top, ...",[kenapa gak bisa transfer ke dana kok gagal mu...
48,47,56,47_mohon_tolong_saya_tidak,"[mohon, tolong, saya, tidak, perbaiki, bisa, l...",[selesai update kenapa saya tidak bisa buka m ...
49,48,52,48_transaksi_qris_data_gagal,"[transaksi, qris, data, gagal, abrik, guna, hi...","[transaksi selalu gagal, transaksi gagal saldo..."
50,49,52,49_jaringan_internet_wifi_padahal,"[jaringan, internet, wifi, padahal, terhubung,...",[ko ga bisa masuk aplikasi nya ya padahal jari...
51,50,50,50_pulsa_sms_verifikasi_udh,"[pulsa, sms, verifikasi, udh, kirim, gagal, mu...",[knp si error mulu udh beberapa kali kirim no ...

# Analyzing

In [46]:
bca_topics = (
    df[df["bank"] == "BCAMobile_reviews"]["topic"]
    .value_counts()
    .head(3)
)

bca_topics

topic
-1     1538
 0      205
 37      78
Name: count, dtype: int64

In [47]:
for topic_id in bca_topics.index:
    print(f"\nTopic {topic_id}")
    print(topic_model.get_topic(topic_id))

Topic -1
[('bisa', np.float64(0.014708756222363608)), ('di', np.float64(0.01417384324086571)), ('mau', np.float64(0.01185509524173038)), ('ini', np.float64(0.011825445632890175)), ('aplikasi', np.float64(0.011764648248019094)), ('nya', np.float64(0.011683583081447199)), ('saya', np.float64(0.011485825381325327)), ('gak', np.float64(0.010939428861994425)), ('lagi', np.float64(0.010660362085852151)), ('ga', np.float64(0.010477625281031952))]

Topic 0
[('saldo', np.float64(0.02549405804455543)), ('saya', np.float64(0.024746587977365876)), ('ada', np.float64(0.017134098483648916)), ('tapi', np.float64(0.016815760858546136)), ('tidak', np.float64(0.016691779731490938)), ('sudah', np.float64(0.01634798607908862)), ('uang', np.float64(0.015840840037111083)), ('dan', np.float64(0.015653425419931772)), ('di', np.float64(0.015095583060225475)), ('transaksi', np.float64(0.015049810484863898))]

Topic 37
[('merah', np.float64(0.22317503060574784)), ('indikator', np.float64(0.17177727403645662)), ('lampu', np.float64(0.13983727932893367)), ('hijau', np.float64(0.09633469618454646)), ('indikatornya', np.float64(0.09587071570288856)), ('terus', np.float64(0.05455257661726311)), ('biru', np.float64(0.04601451011420658)), ('sinyal', np.float64(0.03648992089640257)), ('kenapa', np.float64(0.03096221780192938)), ('lampunya', np.float64(0.02772972129386267))]

In [48]:
for topic_id in bca_topics.index:
    print(f"\n=== Topic {topic_id} ===")
    
    print("Keywords:")
    print(topic_model.get_topic(topic_id))
    
    print("\nSample text:")
    print(
        df[(df["bank"] == "BCAMobile_reviews") & (df["topic"] == topic_id)]
        ["clean_text"]
        .head(5)
        .tolist()
    )

=== Topic -1 ===
Keywords:
[('bisa', np.float64(0.014708756222363608)), ('di', np.float64(0.01417384324086571)), ('mau', np.float64(0.01185509524173038)), ('ini', np.float64(0.011825445632890175)), ('aplikasi', np.float64(0.011764648248019094)), ('nya', np.float64(0.011683583081447199)), ('saya', np.float64(0.011485825381325327)), ('gak', np.float64(0.010939428861994425)), ('lagi', np.float64(0.010660362085852151)), ('ga', np.float64(0.010477625281031952))]

Sample text:
['dikit verivikasi ribet mohon di perbaiki', 'sangat kecewa saya melakukan transfer keterangan gagal tapi saldo saya berkurang', 'update an baru ada bugs', 'gimana sih bca pas lagi transfer tiba tiba error dan disuruh cek mutasi padahal yang dibutuhin bukti transfer bukan mutasi di inbox juga bukti transfernya gak ada', 'ga bisa masuk masuk sampe pulsa habiss emangg tolol']

=== Topic 0 ===
Keywords:
[('saldo', np.float64(0.02549405804455543)), ('saya', np.float64(0.024746587977365876)), ('ada', np.float64(0.017134098483648916)), ('tapi', np.float64(0.016815760858546136)), ('tidak', np.float64(0.016691779731490938)), ('sudah', np.float64(0.01634798607908862)), ('uang', np.float64(0.015840840037111083)), ('dan', np.float64(0.015653425419931772)), ('di', np.float64(0.015095583060225475)), ('transaksi', np.float64(0.015049810484863898))]

Sample text:
['kenapa gaji saya tidak masukmasuk saya sudah menunggu dengan sabar tapi gaji saya yang seharusnya cair di tanggal april masih belum cair juga di tanggal april hari ini pelayanan seperti apa ini sampai gaji saya tidak masukmasuk hingga hari menunggu saya juga butuh uang untuk memenuhi kebutuhan hidup saya tolong ini pihak bca jangan dilamalamakan dong pencairan gaji karyawan yang pakai rekening bca ini sudah sering sekali terjadi gaji selalu terlambat dikirimkan', 'halo bca hp saya yg lama rusak saya pakai hp yg lain pindahkan sim card ke hp itu verifikasi ktp bisa nomor kartu atm sudah diupdate waktu mau request historis transfer minta otp tapi saya cek ga ada otp yg masuk ke hp saya diulang request otp tetep saja gak ada otp masuk ke hp tolong dicek kembali programnya waktu mau kirim otp tampilkan nomor hp yg mau dikirimin otp jadi user bisa cek nomor hp nya udah bener ato belum jadi saya masih ga bisa transaksi apapun iniotp nyasar ke mn', 'kenapasiii mau verifikasi sms gabisa muluuu ada bacaan sementara transaksi tidak dapat diproses silahkan coba beberapa saat lagi tiap coba gitu lagi pulsa guee mubazirrr woyyyy', 'saya ingin menyampaikan keluhan masa iya saya sudah melakukan top up dari bca ke telkomsel sebesar ngga ke kirim pulsanya tapi uang dari bca nya sudah kepotong sudah di cek no telpon nya juga udah bener ngajuin ke halo bca malah di matiin terus gimana tanggung jawabnya', 'daftar online selalu di tolak padahal saya anak rantau harus ada surat domisilisaya bru merantau padahal sedangkan kalo daftar offline cukup ktp aja bisamohon system nya di ubahdan juga pelayanan pas video call nya buruk']

=== Topic 37 ===
Keywords:
[('merah', np.float64(0.22317503060574784)), ('indikator', np.float64(0.17177727403645662)), ('lampu', np.float64(0.13983727932893367)), ('hijau', np.float64(0.09633469618454646)), ('indikatornya', np.float64(0.09587071570288856)), ('terus', np.float64(0.05455257661726311)), ('biru', np.float64(0.04601451011420658)), ('sinyal', np.float64(0.03648992089640257)), ('kenapa', np.float64(0.03096221780192938)), ('lampunya', np.float64(0.02772972129386267))]

Sample text:
['lampu indikator selalu merah padahal sinyal lncarr', 'kenapa ya lampu indikatornya merah terus padahal sinyal bagus tolong diperbaiki', 'kenapa lampu selalu merah transaksi jadi terganggu', 'dari pagi lampu indikator merah terus ga bisa transaksi', 'setelah di update knpa lampu nya merah trus']