In [21]:
!pip install bertopic

Requirement already satisfied: bertopic in /usr/local/lib/python3.12/dist-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.44)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.6.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cu128)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.16.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.5.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)

In [ ]:
!git clone https://github.com/ranslemus/topic_modeling_KBMI4.git
%cd topic_modeling_KBMI4
!git switch gavriel-thesis

Cloning into 'topic_modeling_KBMI4'...
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 290 (delta 31), reused 53 (delta 19), pack-reused 220 (from 2)
Receiving objects: 100% (290/290), 57.64 MiB | 15.52 MiB/s, done.
Resolving deltas: 100% (121/121), done.
Filtering content: 100% (4/4), 294.40 MiB | 14.34 MiB/s, done.
/content/topic_modeling_KBMI4
Updating files: 100% (41/41), done.
Filtering content: 100% (9/9), 1.07 GiB | 12.90 MiB/s, done.
Branch 'gavriel-thesis' set up to track remote branch 'gavriel-thesis' from 'origin'.
Switched to a new branch 'gavriel-thesis'

In [31]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
import plotly.express as px

from transformers import AutoTokenizer, AutoModel
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from tqdm.auto import tqdm
from cuml.manifold import UMAP
from cuml.cluster import HDBSCAN

In [32]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device :", device)

if device.type == "cuda":
    print("GPU :", torch.cuda.get_device_name(0))

Device : cuda
GPU : Tesla T4

In [33]:
df = pd.read_csv("data/preprocessed_data.csv")

df.head()

                               reviewId  ...                                               text
0  e17751da-bf2e-4a8f-a5a8-334206bb93ca  ...  ribet banget nih apk sumpah dikir verif dikit ...
1  3481f1d1-a22f-445f-ae2f-ed8c2c9dca53  ...  kenapa qris enggak bisa di pakai ya daritadi l...
2  af69ec6d-cc97-404e-b86a-e5f5b5f1f711  ...  aplikasi nya sampah kenapa tiba tiba keluar te...
3  32d28ac6-c538-4749-969f-8af060915d96  ...                                              bagus
4  f99259b7-0d45-4422-b667-6c4fd521638b  ...  tidak ada solusi ketika ada kendala di persuli...

[5 rows x 5 columns]

In [34]:
documents = df["text"].astype(str).tolist()

print(f"Total documents : {len(documents):,}")

Total documents : 193,827

# IndoBERT

In [ ]:
MODEL_NAME = "indobenchmark/indobert-base-p1"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModel.from_pretrained(MODEL_NAME)

model.to(device)

model.eval()

e:\anaconda\envs\nlp\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\gavri\.cache\huggingface\hub\models--indobenchmark--indobert-base-p1. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(50000, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

In [ ]:
def mean_pooling(model_output, attention_mask):

    token_embeddings = model_output.last_hidden_state

    input_mask_expanded = (
        attention_mask
        .unsqueeze(-1)
        .expand(token_embeddings.size())
        .float()
    )

    return torch.sum(
        token_embeddings * input_mask_expanded,
        dim=1
    ) / torch.clamp(
        input_mask_expanded.sum(dim=1),
        min=1e-9
    )

In [ ]:
def encode_documents(
    documents,
    batch_size=32,
    max_length=128
):

    embeddings = []

    with torch.no_grad():

        for i in tqdm(
            range(0, len(documents), batch_size)
        ):

            batch = documents[
                i:i+batch_size
            ]

            encoded_input = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=max_length,
                return_tensors="pt"
            )

            encoded_input = {
                k: v.to(device)
                for k, v in encoded_input.items()
            }

            model_output = model(**encoded_input)

            sentence_embeddings = mean_pooling(
                model_output,
                encoded_input["attention_mask"]
            )

            sentence_embeddings = (
                sentence_embeddings
                .cpu()
                .numpy()
            )

            embeddings.append(sentence_embeddings)

    return np.vstack(embeddings)

In [ ]:
embeddings = encode_documents(
    documents,
    batch_size=32,
    max_length=128
)

100%|██████████| 6058/6058 [26:05<00:00,  3.87it/s]

In [ ]:
print(embeddings.shape)

(193827, 768)

In [ ]:
embeddings[0]

array([ 1.32068610e+00,  3.98074418e-01, -6.73392862e-02,  6.81021631e-01,
       -1.96820974e-01,  1.08589363e+00, -8.56553018e-01,  2.23273388e-03,
        8.79841328e-01,  3.65444899e-01, -3.26138228e-01,  4.72277194e-01,
       -8.05487573e-01,  1.67667508e-01, -2.56380171e-01, -4.40765619e-01,
       -4.77702200e-01,  2.61944145e-01, -2.86765069e-01, -2.72093844e-02,
        7.49712348e-01,  1.74879134e-02,  2.77186837e-02, -1.01489611e-01,
       -5.50755799e-01, -4.60477501e-01,  3.93649340e-01,  8.93991292e-01,
       -5.85758351e-02, -1.70096517e-01, -2.30777428e-01,  5.49784362e-01,
        2.69129515e-01,  5.88295817e-01, -7.31480896e-01,  9.41245556e-01,
        4.00836855e-01,  1.14819241e+00, -5.05113244e-01, -9.31886211e-02,
       -1.09638429e+00,  7.68689096e-01, -1.85003400e-01,  1.06485210e-01,
       -8.93403411e-01,  6.15286827e-01,  5.15412211e-01,  8.41604114e-01,
       -5.12369573e-01, -3.84789519e-02, -7.70254806e-02,  3.15342516e-01,
        1.43759996e-01,  1.97320223e-01,  6.44251406e-02,  9.26969200e-02,
        1.66871160e-01, -3.17551941e-01, -6.57300232e-03,  7.28832364e-01,
        1.17630504e-01, -2.11039171e-01,  3.96534353e-01,  4.02093649e-01,
        7.67411441e-02, -3.95548135e-01, -9.91785288e-01,  1.46829128e-01,
        1.36158422e-01,  2.24237025e-01, -1.36944056e-01,  3.34581763e-01,
       -5.07855773e-01, -5.81686556e-01, -5.07551551e-01, -1.42887622e-01,
       -1.09154426e-01,  2.34138384e-01,  4.13504355e-02, -1.38366938e-01,
        2.03886017e-01,  7.67618418e-01, -6.94699958e-02,  4.23143655e-01,
        2.35384321e+00, -2.43400410e-01, -7.88966596e-01, -4.02959548e-02,
       -9.13855612e-01,  4.39103216e-01,  3.22443172e-02, -8.17744076e-01,
        2.02730298e-01,  8.90335798e-01, -1.23405778e+00,  3.80794406e-01,
        5.58330297e-01,  3.81324708e-01,  2.10829422e-01, -6.51476532e-02,
       -1.70844048e-01, -2.28593946e-01, -6.03919104e-02, -6.23181462e-01,
        1.73540592e-01, -1.07696764e-01, -5.86243212e-01, -2.11819619e-01,
       -1.49726808e+00, -1.38520277e+00,  3.51368159e-01,  3.65723670e-01,
       -6.46653473e-01, -2.13271335e-01,  9.75981891e-01, -4.48155165e-01,
       -3.53427500e-01, -2.51750857e-01, -7.31218338e-01, -5.90124369e-01,
        1.09979615e-01,  6.34382010e-01, -1.77804917e-01,  1.66976944e-01,
        9.46006656e-01,  1.93851292e-01,  4.89735216e-01,  1.13262272e+00,
        4.27637786e-01,  1.33891031e-02, -3.42409201e-02,  4.98047709e-01,
        1.79578558e-01, -4.59296793e-01, -2.48700008e-01,  4.65834200e-01,
        5.70779264e-01,  9.39915776e-01,  3.38124335e-02, -2.54043072e-01,
        6.42501593e-01,  1.15248159e-01, -7.53188550e-01, -4.67682421e-01,
        4.27319944e-01, -1.09846592e+00,  1.00973678e+00, -2.71443605e-01,
        1.11572993e+00, -8.28158081e-01, -1.70605327e-03,  6.11813605e-01,
       -1.29918739e-01,  3.21477830e-01,  2.33686134e-01,  8.13872218e-01,
       -8.51101279e-02,  5.91713190e-01,  6.10243440e-01,  7.80989826e-01,
        9.60151672e-01, -2.83218861e-01,  4.48849618e-01,  1.15441453e+00,
       -3.27395946e-01, -5.36414564e-01,  5.21873891e-01, -4.73562002e-01,
        8.83897245e-01,  5.32779932e-01,  3.47251326e-01, -3.95090938e-01,
        5.46663627e-03, -4.57861185e-01,  8.60277936e-02,  4.78932649e-01,
       -5.99484265e-01,  2.43796766e-01, -2.84989178e-01,  1.28640461e+00,
       -3.20430137e-02,  1.02549672e+00,  3.64079952e-01,  1.01266932e+00,
        6.86015964e-01,  5.06257892e-01, -1.39047364e-02, -2.49544397e-01,
       -2.01730192e-01, -3.55040461e-01,  2.17349514e-01, -3.10605288e-01,
        4.96544093e-02,  4.68063533e-01, -4.06042218e-01,  6.34458542e-01,
       -1.48225188e+00, -5.98837852e-01, -4.79338825e-01,  4.75240469e-01,
        1.01131499e-01, -1.03001881e+00,  4.70870525e-01, -5.01111865e-01,
       -8.73190701e-01, -1.40394926e-01, -8.34171236e-01,  8.22845519e-01,
        4.79154825e-01,  6.30910516e-01,  4.33221489e-01, -1.24963492e-01,
       -4.95444238e-01, -1.03360748e+00, -2.80651152e-01,  1.81038007e-01,
       -9.04925823e-01, -4.63735640e-01,  2.37010390e-01, -5.75082377e-02,
        1.56191850e+00, -3.10521781e-01, -3.93302202e-01,  4.26682144e-01,
        7.10006356e-02, -6.79919183e-01,  5.78375682e-02,  2.67210454e-01,
       -4.73383397e-01,  4.08994466e-01, -9.94374529e-02,  3.71809363e-01,
       -1.18119705e+00,  1.78029031e-01,  1.00962043e+00, -7.78881252e-01,
        3.93338650e-01,  4.60263222e-01, -4.91459012e-01, -3.06426793e-01,
       -1.56073989e-02, -2.89911121e-01,  4.52835411e-01, -3.70277584e-01,
        4.03268216e-03, -1.19615860e-01, -7.93525040e-01, -3.08781564e-01,
       -2.38252133e-01, -3.10204357e-01,  5.84676504e-01,  4.32316691e-01,
       -2.25424305e-01, -1.08745754e+00, -4.58609015e-01,  5.84580541e-01,
       -6.19895041e-01, -1.44136995e-01, -4.14401203e-01, -4.04785991e-01,
       -1.50961623e-01, -1.36438251e-01,  1.32456017e+00,  3.62260103e-01,
        2.58642405e-01,  1.05211723e+00,  3.90847027e-01, -4.54845697e-01,
        1.14747941e-01, -5.10243058e-01, -4.83079135e-01,  6.37414157e-01,
        5.00950277e-01, -1.56217799e-01, -8.06688294e-02,  9.62534025e-02,
       -6.05982602e-01,  1.65843889e-01, -3.24442774e-01,  6.62505686e-01,
        1.97196707e-01,  2.09650755e-01, -6.18236780e-01,  4.59217042e-01,
       -6.22553229e-01,  5.31795740e-01, -8.59072581e-02, -4.46357012e-01,
       -1.19725369e-01, -1.32004917e-01,  3.05085927e-01,  6.77930936e-02,
       -2.14511204e+00,  2.11259559e-01, -5.52598476e-01,  7.05499053e-01,
       -4.48397517e-01,  5.05941868e-01, -9.78154361e-01, -2.54443169e-01,
        8.96975219e-01,  2.74552464e-01,  1.63760021e-01, -7.25740716e-02,
       -6.40731931e-01, -8.03754210e-01, -9.81565118e-01,  1.13660789e+00,
       -6.57600284e-01, -4.07155871e-01,  7.29446948e-01, -5.03279984e-01,
        1.36841610e-01, -7.14634061e-01,  1.06431854e+00,  1.99773148e-01,
       -7.93407977e-01, -8.75679374e-01,  5.47044933e-01,  9.93124992e-02,
       -1.19988072e+00,  3.65687281e-01, -7.50816584e-01, -2.06586838e-01,
        5.04621148e-01,  1.50598335e+00, -7.38020420e-01,  6.01834893e-01,
        1.16896078e-01,  6.64042890e-01,  1.28970388e-02, -6.17920399e-01,
        9.87946928e-01, -2.67011404e-01, -1.57298136e+00,  5.32387793e-02,
        8.71281147e-01,  4.18203734e-02,  4.74119961e-01, -4.25215989e-01,
       -2.83039868e-01, -5.45059860e-01, -1.20433652e+00,  1.69673920e-01,
        3.71745080e-01, -2.97478974e-01, -1.16130161e+00, -1.11649597e+00,
        1.18806171e+00, -7.57759809e-01,  5.79187334e-01, -9.71418917e-01,
        4.46810246e-01, -2.17064187e-01,  2.99400955e-01, -5.75874329e-01,
       -1.19823977e-01,  4.81698543e-01, -4.76987064e-01,  9.96646762e-01,
        1.72375941e+00, -1.17608391e-01,  4.76761088e-02, -8.75444651e-01,
        5.74597903e-03,  1.07782155e-01, -5.18173695e-01,  4.83047366e-01,
       -4.92979109e-01, -7.08706155e-02,  1.35232329e-01, -1.78214610e-01,
        5.93065798e-01, -5.93796313e-01,  3.49066615e-01,  5.20951569e-01,
        3.99903953e-01, -3.17482859e-01, -2.20976919e-01,  9.19342339e-02,
       -6.99684918e-02, -9.63346124e-01,  1.14098080e-01, -8.28279555e-01,
       -5.82324326e-01,  4.46441919e-01,  5.23228228e-01, -2.08012030e-01,
       -2.76594818e-01,  4.38171774e-01, -2.36038774e-01,  1.22004330e+00,
       -5.28028190e-01,  1.20797133e+00, -6.63168803e-02,  2.33926877e-01,
       -3.93803000e-01,  7.06381977e-01, -5.02431870e-01,  6.26010001e-01,
       -3.37431103e-01,  6.95811570e-01, -3.70661646e-01,  3.92702758e-01,
        5.30606747e-01,  1.50733009e-01, -5.40337265e-02,  9.73825097e-01,
       -9.01372433e-01,  1.91192832e-02,  6.08973298e-03, -7.55193830e-01,
       -6.56889796e-01, -1.95908975e-02,  5.70733011e-01, -5.71866214e-01,
       -6.93043172e-01,  3.77183855e-01, -6.15951717e-01, -9.18830216e-01,
       -2.64288113e-02,  4.00798976e-01,  7.01071799e-01,  1.66517794e-01,
        3.97528782e-02, -1.57192260e-01, -6.43103957e-01,  6.91649258e-01,
        1.76289916e-01,  5.78183591e-01, -6.29187346e-01,  6.76184475e-01,
        5.83872572e-02,  3.73771548e-01, -2.43174866e-01, -1.24763274e+00,
       -1.00830543e+00, -2.96127591e-02,  3.99818659e-01,  5.29628098e-01,
        2.32557997e-01, -4.06963408e-01, -7.13303328e-01,  2.85062164e-01,
        2.72896320e-01, -1.24664438e+00,  1.12165189e+00,  6.86406314e-01,
       -1.24929023e+00, -2.48055324e-01,  8.92127872e-01, -9.65406954e-01,
        3.61416578e-01, -2.37233505e-01,  8.51591349e-01,  4.14230913e-01,
        4.28255230e-01, -9.64156628e-01,  2.19384909e-01,  8.98636758e-01,
       -2.37010032e-01, -1.43071517e-01,  1.25249195e+00, -1.56451285e-01,
       -2.94685718e-02,  4.57765162e-01,  1.95857495e-01,  1.47405723e-02,
       -7.96425939e-02, -9.39341784e-01,  1.35356739e-01,  8.96434858e-02,
       -9.96197984e-02, -1.11121166e+00,  6.47905648e-01, -3.41197252e-01,
       -4.18945819e-01,  8.28506798e-02,  2.42028177e-01, -8.12286675e-01,
       -1.11473918e+00,  6.84771128e-03,  1.45654273e+00, -5.26021540e-01,
       -1.53614774e-01,  1.09242296e+00,  3.98850620e-01, -1.43717378e-01,
        5.69157660e-01, -9.09473300e-02,  3.15044075e-01, -5.02384543e-01,
       -1.02553904e-01, -4.22195494e-02, -1.36073709e+00, -1.32115126e-01,
       -7.36364603e-01, -9.83517170e-02,  2.28154212e-01,  3.05156171e-01,
        1.61990196e-01, -6.56169653e-02, -1.23208463e-01, -8.83706152e-01,
       -7.18316555e-01,  5.25220454e-01,  5.13223588e-01,  7.48853445e-01,
        3.95249099e-01, -5.30877233e-01,  6.13541827e-02,  6.13029957e-01,
       -8.02250385e-01, -2.01805726e-01,  5.15399933e-01, -3.69936317e-01,
        2.79240608e-01,  4.49401475e-02,  5.77150822e-01,  8.46502125e-01,
       -4.12990898e-01,  6.90215588e-01, -6.79844141e-01,  1.01232791e+00,
       -7.98809230e-02,  5.26831090e-01,  1.89411271e+00, -5.53198397e-01,
        3.58845919e-01, -2.29904681e-01,  6.17840827e-01, -2.64708310e-01,
        1.43279397e+00, -9.60643589e-02, -3.35104406e-01,  2.02044602e-02,
        2.26821095e-01,  2.80677587e-01,  2.90783904e-02,  4.49717306e-02,
        8.91394019e-01,  2.47110933e-01,  3.79103780e-01,  3.55358779e-01,
        9.27963138e-01,  6.45975530e-01,  7.19993114e-01, -3.23043048e-01,
        2.69192308e-01, -1.82333827e+00, -8.79662856e-02,  1.47780180e-01,
       -2.29923904e-01,  2.33274162e-01,  2.84974724e-01, -5.92382513e-02,
       -7.81367645e-02, -3.86418253e-01, -1.72131851e-01, -1.13201082e-01,
        5.78283705e-02, -9.18726683e-01, -2.72824559e-02,  3.41069043e-01,
        1.51793361e-01, -1.43663719e-01, -7.28416815e-02, -1.91382542e-01,
        7.87875414e-01, -3.77728552e-01,  1.27546072e-01, -1.43221214e-01,
       -1.62158072e-01,  2.09145904e-01,  4.28880379e-02,  5.47434807e-01,
       -7.07123756e-01,  1.31952479e-01, -6.16113305e-01, -5.28996527e-01,
       -1.71640575e+00, -7.72513151e-02,  2.91635096e-01, -7.00255930e-01,
       -6.47592396e-02, -9.87615064e-02, -1.71652174e+00,  7.16464877e-01,
       -1.46261001e+00,  6.55964375e-01,  1.93406239e-01,  5.66286802e-01,
       -7.35274255e-01,  4.60251838e-01, -1.88378453e-01, -1.27285257e-01,
       -2.92627513e-01,  7.38148868e-01,  6.96693301e-01,  4.24642116e-01,
       -2.33504593e-01, -1.16243251e-01, -7.04835892e-01, -1.85638309e-01,
        3.01404987e-02, -6.85934067e-01, -5.53824008e-01,  3.04810286e-01,
       -4.03944135e-01,  4.50366586e-01,  1.43963024e-01, -2.06660807e-01,
        1.29381835e-01,  7.05321848e-01, -3.03266197e-01,  7.01349854e-01,
        1.14439547e-01, -6.09927654e-01,  3.64675462e-01, -5.80378234e-01,
       -6.90393567e-01, -3.01735818e-01, -6.29128456e-01, -5.74533761e-01,
        4.89604831e-01, -6.00556210e-02, -1.59624070e-01, -6.04924560e-01,
        2.22806737e-01, -7.65102133e-02, -7.08519816e-02,  2.57658213e-01,
        1.54485460e-02, -1.08444369e+00,  1.61512434e-01,  2.95386732e-01,
       -5.25762081e-01,  8.84418190e-02,  1.71786278e-01,  2.31138930e-01,
        1.81172371e-01, -3.34468126e-01,  1.70263064e+00,  5.66750050e-01,
       -1.37284249e-01, -4.80294049e-01, -5.56027412e-01,  2.45315328e-01,
       -6.90607548e-01,  1.20199220e-02, -9.89959717e-01, -3.02113652e-01,
       -5.10749876e-01, -1.43321753e-01,  1.02990093e-02, -1.06621943e-01,
       -9.87287164e-02,  5.79333007e-01, -7.77581573e-01, -2.47626618e-01,
       -1.97518766e-01, -3.40246528e-01,  1.84063524e-01, -7.18436539e-01,
        5.16621292e-01, -2.23914728e-01, -1.03504872e+00, -7.51089931e-01,
       -1.82342336e-01, -8.48187268e-01,  1.70495674e-01,  1.74984738e-01,
        5.53579152e-01,  9.49121356e-01,  7.24094629e-01,  5.35775088e-02,
        5.57496846e-01,  7.08502948e-01,  7.12258041e-01,  2.75276005e-01,
        6.69240177e-01, -3.24312389e-01, -6.42077029e-01,  2.88151979e-01,
        2.34037209e-02, -5.30521750e-01, -3.51715177e-01,  8.53334665e-01,
        1.01677381e-01, -1.15190709e+00,  4.42010194e-01,  8.81750226e-01,
        9.15112719e-03,  1.16703737e+00, -5.65890551e-01,  3.73938948e-01,
       -8.24945986e-01, -8.37257922e-01,  2.46420979e-01, -3.65867853e-01,
       -1.22957754e+00, -1.22171402e+00, -3.66554141e-01,  2.81086653e-01,
        1.54189929e-01,  6.35578707e-02, -2.14482937e-02,  1.47708327e-01,
        7.27597103e-02,  6.07389621e-02, -5.40756918e-02,  8.55434895e-01,
       -7.29310215e-01,  7.47794032e-01,  9.48276520e-01,  3.25161606e-01,
       -4.43915784e-01,  2.00024888e-01, -2.51481980e-01, -7.63259009e-02,
        8.93962860e-01,  3.45730752e-01,  8.03814411e-01,  3.65651220e-01,
        2.60471910e-01,  3.34632158e-01,  1.43781066e-01, -9.87426102e-01,
        8.54340076e-01, -1.01844895e+00,  5.03772020e-01, -5.18127918e-01,
        2.16342092e-01,  8.65129828e-01, -5.57527423e-01,  4.18843001e-01,
       -6.17910206e-01,  8.52742851e-01, -6.14989758e-01,  4.50309515e-01,
       -1.29673099e-02,  3.33035856e-01, -7.19268024e-01,  4.64853108e-01,
        3.06917012e-01, -4.57154185e-01, -9.34969425e-01, -4.71497148e-01,
        1.53724521e-01,  5.93027212e-02, -6.47993684e-01, -1.47972241e-01,
        4.52822834e-01, -3.94363195e-01,  1.31415844e-01, -1.65421963e+00,
       -1.17043175e-01,  3.45552355e-01,  2.97790021e-01, -4.77463841e-01,
       -3.94171000e-01, -3.26709539e-01,  3.30757827e-01,  4.77451086e-01,
        8.50856185e-01,  7.37184361e-02, -8.29868436e-01, -4.46284801e-01],
      dtype=float32)

In [ ]:
norms = np.linalg.norm(embeddings, axis=1)

print("Minimum Norm :", norms.min())
print("Maximum Norm :", norms.max())
print("Average Norm :", norms.mean())
print("Std Norm :", norms.std())

Minimum Norm : 12.87398
Maximum Norm : 26.276495
Average Norm : 18.317768
Std Norm : 2.1703527

In [ ]:
print("NaN :", np.isnan(embeddings).sum())
print("Inf :", np.isinf(embeddings).sum())

NaN : 0
Inf : 0

In [ ]:
np.save(
    "indobert_embeddings.npy",
    embeddings
)

# BERTopic

In [35]:
embeddings = np.load("indobert_embeddings.npy")

print("Embedding Shape :", embeddings.shape)

Embedding Shape : (193827, 768)

In [36]:
vectorizer_model = CountVectorizer()

baseline UMAP for testing purpose

In [37]:
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    metric="cosine",
    min_dist=0.0,
    random_state=42
)

baseline HDBSCAN

In [38]:
hdbscan_model = HDBSCAN(
    min_cluster_size=30,
    metric="euclidean",
    prediction_data=True
)

In [39]:
topic_model = BERTopic(
    embedding_model=None,
    calculate_probabilities=False,
    vectorizer_model=vectorizer_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    verbose=True
)

In [40]:
topics, probabilities = topic_model.fit_transform(
    documents,
    embeddings
)

2026-08-05 04:20:57,561 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-08-05 04:21:20,234 - BERTopic - Dimensionality - Completed ✓
2026-08-05 04:21:20,247 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-05 04:21:26,182 - BERTopic - Cluster - Completed ✓
2026-08-05 04:21:26,247 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-05 04:21:34,011 - BERTopic - Representation - Completed ✓

# Evaluation

Basic Statistics

In [42]:
topic_info = topic_model.get_topic_info()

topic_info.head(10)

   Topic  ...                                Representative_Docs
0     -1  ...  [sering gangguan, sering gangguan, sering gang...
1      0  ...  [kenapa livin saya enggak bisa transfer ya pad...
2      1  ...                              [bagus, bagus, bagus]
3      2  ...                                       [ok, ok, ok]
4      3  ...                           [mantap, mantap, mantap]
5      4  ...               [error mulu, error mulu, error mulu]
6      5  ...  [aplikasi menyusahkan, aplikasi menyusahkan, a...
7      6  ...         [sangat bagus, sangat bagus, sangat bagus]
8      7  ...                              [jelek, jelek, jelek]
9      8  ...                                    [oke, oke, oke]

[10 rows x 5 columns]

In [43]:
num_topics = len(topic_info) - 1

outlier_count = (np.array(topics) == -1).sum()

outlier_percentage = (
    outlier_count / len(topics)
) * 100

print(f"Topics              : {num_topics}")
print(f"Outliers            : {outlier_count:,}")
print(f"Outlier Percentage  : {outlier_percentage:.2f}%")

Topics              : 60
Outliers            : 3,166
Outlier Percentage  : 1.63%

Topic Size

In [44]:
topic_info[["Topic","Count"]]

    Topic   Count
0      -1    3166
1       0  186223
2       1     468
3       2     334
4       3     269
..    ...     ...
56     55      34
57     56      33
58     57      32
59     58      32
60     59      30

[61 rows x 2 columns]

Top Words

In [45]:
for topic in topic_info.Topic:

    if topic == -1:
        continue

    print("="*80)

    print(f"Topic {topic}")

    print(topic_model.get_topic(topic))

================================================================================
Topic 0
[('enggak', np.float64(0.012938851404366097)), ('bisa', np.float64(0.012782520657229485)), ('di', np.float64(0.012745747684432747)), ('saya', np.float64(0.011720887493554235)), ('sudah', np.float64(0.011467851799374887)), ('tidak', np.float64(0.011206780866011384)), ('ini', np.float64(0.010630911398713312)), ('aplikasi', np.float64(0.010503611325205338)), ('nya', np.float64(0.010223064399522233)), ('mau', np.float64(0.009966900881050289))]
================================================================================
Topic 1
[('bagus', np.float64(1.888466072558088)), ('5idak', np.float64(0.023233946283275957)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 2
[('ok', np.float64(3.986018133932663)), ('good', np.float64(0.048453425465833415)), ('mntp', np.float64(0.027095390315605993)), ('bannget', np.float64(0.02645970645904477)), ('okay', np.float64(0.024485191936546042)), ('tok', np.float64(0.02223950761820026)), ('lanjutkan', np.float64(0.014309906825184295)), ('apl', np.float64(0.012345988265416271)), ('no', np.float64(0.007556348881386302)), ('lemot', np.float64(0.0073846290180751215))]
================================================================================
Topic 3
[('mantap', np.float64(4.474618873401203)), ('jiwa', np.float64(0.028125601963089514)), ('puas', np.float64(0.01730985583282831)), ('jelek', np.float64(0.00918253575746349)), ('juga', np.float64(0.005980297262194286)), ('banget', np.float64(0.005100758847905797)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 4
[('mulu', np.float64(0.2403314315024979)), ('gangguan', np.float64(0.2303277275538441)), ('lemot', np.float64(0.21124268074392422)), ('error', np.float64(0.17874819518859156)), ('busuk', np.float64(0.16763370501861002)), ('eror', np.float64(0.15998240314168988)), ('cacat', np.float64(0.1541268632935725)), ('ribet', np.float64(0.14954023848029016)), ('sampah', np.float64(0.13281312600161715)), ('banyak', np.float64(0.1272094714071987))]
================================================================================
Topic 5
[('menyusahkan', np.float64(0.24150462828387356)), ('guna', np.float64(0.1878200327494716)), ('lemot', np.float64(0.1863003439466264)), ('bug', np.float64(0.17095557694912641)), ('suka', np.float64(0.1631260538834266)), ('aneh', np.float64(0.1245924252255318)), ('gangguan', np.float64(0.11366172642331003)), ('susah', np.float64(0.11232369580257237)), ('jelas', np.float64(0.11168284567120507)), ('masuk', np.float64(0.1041761797035422))]
================================================================================
Topic 6
[('bagus', np.float64(0.9204772648218922)), ('sangat', np.float64(0.7500251656656665)), ('cukup', np.float64(0.19246399052929863)), ('apak', np.float64(0.0305547419369241)), ('trouble', np.float64(0.018509197030526437)), ('cepat', np.float64(0.012706846952898766)), ('dapat', np.float64(0.010491333207653306)), ('sering', np.float64(0.005852833585775048)), ('buka', np.float64(0.005465808770914848)), ('tidak', np.float64(0.0027794124867836388))]
================================================================================
Topic 7
[('jelek', np.float64(2.485033720380685)), ('super', np.float64(0.04724366603773206)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 8
[('oke', np.float64(4.27020889674385)), ('baiklah', np.float64(0.09717706804749016)), ('yes', np.float64(0.08845101873452109)), ('okay', np.float64(0.08185049875931107)), ('langsung', np.float64(0.025998628672303237)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 9
[('good', np.float64(5.507077900088151)), ('oo', np.float64(0.08011445565522798)), ('lah', np.float64(0.04417853808046226)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 10
[('lumayan', np.float64(4.373481674703699)), ('mantap', np.float64(0.04604141988687354)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 11
[('keseringan', np.float64(0.549332446527842)), ('eror', np.float64(0.2867053066828705)), ('bagus', np.float64(0.2390527902914287)), ('error', np.float64(0.18982849266811827)), ('update', np.float64(0.12765836571745123)), ('aplikasi', np.float64(0.12583570992994686)), ('selalu', np.float64(0.10478522538177397)), ('seering', np.float64(0.057351162141349596)), ('tidak', np.float64(0.05263329540761858)), ('hobi', np.float64(0.04888082614276165))]
================================================================================
Topic 12
[('baik', np.float64(1.2909775204206289)), ('sangat', np.float64(0.8096215266428982)), ('terlalu', np.float64(0.03557722622493809)), ('100', np.float64(0.026925828459636123)), ('ok', np.float64(0.026432880502746357)), ('sering', np.float64(0.019040230779040348)), ('dibuka', np.float64(0.014041414589559261)), ('update', np.float64(0.013955747690630457)), ('brimo', np.float64(0.008768831933624353)), ('tidak', np.float64(0.004520943095591108))]
================================================================================
Topic 13
[('memuaskan', np.float64(1.4096812828787622)), ('luar', np.float64(0.7156562492978326)), ('biasa', np.float64(0.6556015739146287)), ('terimakasih', np.float64(0.37410558980684344)), ('sangat', np.float64(0.2613125955975516)), ('hebat', np.float64(0.12363903000246043)), ('wassada', np.float64(0.09558527023558266)), ('luarbiasa', np.float64(0.07851685758594089)), ('berkualitas', np.float64(0.07073512035697253)), ('recommended', np.float64(0.059679546149065996))]
================================================================================
Topic 14
[('baik', np.float64(2.794170523650128)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 15
[('unable', np.float64(0.3408342132951645)), ('identity', np.float64(0.33868316471832605)), ('your', np.float64(0.3307651147795358)), ('authenticate', np.float64(0.3083540109689702)), ('208', np.float64(0.12356048006622679)), ('tapi', np.float64(0.05846308525319385)), ('tulisan', np.float64(0.05555364979171717)), ('muncul', np.float64(0.031039450842532162)), ('kenapa', np.float64(0.030355358633793343)), ('authentic', np.float64(0.02518803484633767))]
================================================================================
Topic 16
[('ribet', np.float64(1.8348991424338306)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 17
[('buruk', np.float64(2.5273914386115184)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 18
[('cukup', np.float64(0.4558824476131774)), ('sering', np.float64(0.36391408827681954)), ('sendiri', np.float64(0.2760793562123734)), ('keluar', np.float64(0.2640683699124529)), ('lemot', np.float64(0.16722611518350758)), ('cukuplah', np.float64(0.14221627240008552)), ('update', np.float64(0.12447626569223617)), ('sekarang', np.float64(0.0950998937360728)), ('hapir', np.float64(0.07489804005745737)), ('uwang', np.float64(0.0616055413970419))]
================================================================================
Topic 19
[('payah', np.float64(2.919796364471467)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 20
[('membantu', np.float64(1.6599151960017775)), ('sangat', np.float64(0.8469602363191231)), ('sangatt', np.float64(0.06304180150814728)), ('mudah', np.float64(0.026852166023770344)), ('saja', np.float64(0.008694641350541828)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 21
[('ribet', np.float64(1.7757088475166103)), ('aga', np.float64(0.2189341115329295)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 22
[('sulit', np.float64(0.25000750576065905)), ('susah', np.float64(0.23728541937627226)), ('buka', np.float64(0.2201415666912495)), ('mulu', np.float64(0.1915899383707358)), ('error', np.float64(0.18504736458785784)), ('gangguan', np.float64(0.1696443677959851)), ('selalu', np.float64(0.11428928141525287)), ('diskripsi', np.float64(0.08131881199146584)), ('di', np.float64(0.0798646124346151)), ('recommend', np.float64(0.05896522634166075))]
================================================================================
Topic 23
[('bermanfaat', np.float64(1.1769840260145288)), ('puas', np.float64(1.0230660153567495)), ('sangat', np.float64(0.6142192968684718)), ('membantu', np.float64(0.3828565540315126)), ('berguna', np.float64(0.27145838951176793)), ('puaskan', np.float64(0.10519167159779862)), ('nice', np.float64(0.07915762201982925)), ('sungguh', np.float64(0.04932779179702203)), ('sekali', np.float64(0.04151513227427556)), ('cukup', np.float64(0.03642359761857861))]
================================================================================
Topic 24
[('mengecewakan', np.float64(0.6572888034127702)), ('sangat', np.float64(0.6227293843554681)), ('puas', np.float64(0.429599149305648)), ('kurang', np.float64(0.3769063281816767)), ('jelek', np.float64(0.3729171959683933)), ('memuaskan', np.float64(0.18973278187506362)), ('lemotd', np.float64(0.0843272078098055)), ('sungguh', np.float64(0.03954376697777799)), ('amat', np.float64(0.02929845785168159)), ('gangguan', np.float64(0.01878706221872893))]
================================================================================
Topic 25
[('mntap', np.float64(2.3388816354986948)), ('jos', np.float64(1.6635146140737287)), ('top', np.float64(0.72601642835807)), ('mntaaff', np.float64(0.1676418585670219)), ('markotop', np.float64(0.15697834069209948)), ('hot', np.float64(0.11940975266013024)), ('force', np.float64(0.09665060465201682)), ('close', np.float64(0.09096875542332658)), ('ruwet', np.float64(0.080389869609711)), ('up', np.float64(0.03894955954026967))]
================================================================================
Topic 26
[('baik', np.float64(2.74681170121538)), ('saat', np.float64(0.03645579696093595)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 27
[('suka', np.float64(0.5773792957965427)), ('cacat', np.float64(0.4699081534115391)), ('eror', np.float64(0.37936947829515627)), ('kebanyakan', np.float64(0.3467227116981892)), ('maintenance', np.float64(0.3115003372819582)), ('jelas', np.float64(0.22060809021472605)), ('apk', np.float64(0.162615414568322)), ('tidak', np.float64(0.06715725726613117)), ('tak', np.float64(0.06304049303603441)), ('administrasi', np.float64(0.045746789300505034))]
================================================================================
Topic 28
[('mantap', np.float64(2.67697969913679)), ('mantab', np.float64(1.5150163246143618)), ('mantapp', np.float64(0.17296382233105434)), ('maknyos', np.float64(0.17296382233105434)), ('mantapn', np.float64(0.17296382233105434)), ('mantapl', np.float64(0.17296382233105434)), ('mantapz', np.float64(0.17296382233105434)), ('mantabz', np.float64(0.17296382233105434)), ('puass', np.float64(0.14207812325075017)), ('pp', np.float64(0.12895888617403198))]
================================================================================
Topic 29
[('lelet', np.float64(3.2565900954272573)), ('jelas', np.float64(0.0673041631163571)), ('aplikasi', np.float64(0.027947147734295623)), ('enggak', np.float64(0.01536515922806617)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 30
[('error', np.float64(2.003745200385693)), ('crash', np.float64(0.3996974911315165)), ('buffering', np.float64(0.26606997112545777)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 31
[('keseringan', np.float64(1.1421305916866749)), ('apk', np.float64(0.3843637071614883)), ('maintenance', np.float64(0.23622108910548492)), ('tahi', np.float64(0.19265854379208497)), ('eror', np.float64(0.14944858235869793)), ('lemot', np.float64(0.14400026585246486)), ('terburuk', np.float64(0.14176951034258614)), ('error', np.float64(0.10436172918675483)), ('terlali', np.float64(0.09447770504617098)), ('busuk', np.float64(0.08290381490027118))]
================================================================================
Topic 32
[('terbaik', np.float64(1.1122753601904511)), ('cukup', np.float64(0.7236447285907966)), ('membantu', np.float64(0.6914900959451963)), ('terima', np.float64(0.6401372705063517)), ('kasih', np.float64(0.4583623644083405)), ('terproteksi', np.float64(0.13128579285369185)), ('eror', np.float64(0.0243079019499087)), ('terus', np.float64(0.012112438990724289)), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 33
[('baik', np.float64(2.7393828663236546)), ('layanan', np.float64(0.06794329795672034)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 34
[('tolol', np.float64(1.1696025898574964)), ('eror', np.float64(0.6725186206141407)), ('apk', np.float64(0.5765455607422325)), ('podol', np.float64(0.14171655756925647)), ('koruptor', np.float64(0.11804181535454668)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 35
[('keren', np.float64(4.099057991291712)), ('barus', np.float64(0.16607026364788738)), ('manfaat', np.float64(0.1234994805270007)), ('hebat', np.float64(0.11944787644305499)), ('luar', np.float64(0.07682185726925887)), ('biasa', np.float64(0.07037531019422567)), ('sangat', np.float64(0.059401068590470354)), ('membantu', np.float64(0.057222011927668286)), ('bri', np.float64(0.03399165404228171)), ('daftar', np.float64(0.03237890498909336))]
================================================================================
Topic 36
[('ruwet', np.float64(1.2192463557472835)), ('force', np.float64(0.7678353591799113)), ('close', np.float64(0.7226962236408722)), ('terus', np.float64(0.2569182892588074)), ('tahi', np.float64(0.0577975631376255)), ('error', np.float64(0.025046815004821164)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 37
[('gangguan', np.float64(1.0974235654664417)), ('mulu', np.float64(1.0328239206422425)), ('sial', np.float64(0.07280609610903577)), ('melulu', np.float64(0.050310464776402025)), ('update', np.float64(0.012672460546664438)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 38
[('force', np.float64(1.534047387790732)), ('close', np.float64(1.4438645482888461)), ('closee', np.float64(0.11393192506075994)), ('auto', np.float64(0.055386505179361306)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 39
[('ribet', np.float64(1.8348991424338306)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 40
[('membantu', np.float64(1.6880493518662145)), ('sangat', np.float64(0.8761657617094377)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 41
[('trouble', np.float64(1.5629694806777394)), ('kacau', np.float64(0.648021628470271)), ('sering', np.float64(0.4942299903645187)), ('tai', np.float64(0.3613592034639023)), ('hancur', np.float64(0.07613438548068371)), ('mulai', np.float64(0.06228447714378993)), ('berulang', np.float64(0.053321617170259655)), ('kadang', np.float64(0.045434278532467155)), ('force', np.float64(0.044873495017007804)), ('close', np.float64(0.04223549358940162))]
================================================================================
Topic 42
[('buruk', np.float64(2.5273914386115184)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 43
[('sampah', np.float64(1.7393411309057938)), ('aplikasi', np.float64(0.39108091989722654)), ('tolol', np.float64(0.04907423453947537)), ('gangguan', np.float64(0.02914403241623334)), ('mulu', np.float64(0.027428474082989956)), ('update', np.float64(0.014134667532818026)), ('terus', np.float64(0.012888877387565589)), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 44
[('jelek', np.float64(0.9963051296847886)), ('aplikasi', np.float64(0.39108091989722654)), ('abal', np.float64(0.16214836052867412)), ('bodoh', np.float64(0.14239682685369892)), ('labil', np.float64(0.12561725070801738)), ('lelet', np.float64(0.09295540185302766)), ('palsu', np.float64(0.0927418285893558)), ('penipu', np.float64(0.07575626058056081)), ('minus', np.float64(0.0694935657107194)), ('', 1e-05)]
================================================================================
Topic 45
[('gangguan', np.float64(1.2670487535713248)), ('kebanyakan', np.float64(0.9068529940839375)), ('gejala', np.float64(0.16062533697090747)), ('telek', np.float64(0.1303707395352623)), ('pemaksaan', np.float64(0.1272399003755486)), ('apakah', np.float64(0.1191429799769067)), ('hu', np.float64(0.1138757558112447)), ('cacat', np.float64(0.0819362950061849)), ('eror', np.float64(0.06614937251942368)), ('banyak', np.float64(0.03381329040917343))]
================================================================================
Topic 46
[('tolol', np.float64(1.863529485275341)), ('aplikasi', np.float64(0.41222042908086043)), ('sesat', np.float64(0.11308292591746921)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 47
[('cukup', np.float64(1.480077811338728)), ('baik', np.float64(1.397085261825064)), ('lumayan', np.float64(0.2985208809953573)), ('begitu', np.float64(0.035443544516023676)), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05), ('', 1e-05)]
================================================================================
Topic 48

Representative Reviews

In [46]:
representative_docs = topic_model.get_representative_docs()

for topic in representative_docs:

    if topic == -1:
        continue

    print("="*100)

    print(f"Topic {topic}")

    print()

    for doc in representative_docs[topic][:5]:

        print("-", doc)

    print()

====================================================================================================
Topic 0

- kenapa livin saya enggak bisa transfer ya padahal jaringan bagus dan enggak ada salah pin atau pasword sudah di pindah ke hp lain tetap enggak bisa tranfer
- kenapa saya tidak bisa login di brimo
- kenapa sih sering banget harus di update terus mending habis di update enggak lemot kalo mau masuk perbaiki lagi jangan malah sering-sering suruh di update lama-lama enggak mau pakai lagi

====================================================================================================
Topic 1

- bagus
- bagus
- bagus

====================================================================================================
Topic 2

- ok
- ok
- ok

====================================================================================================
Topic 3

- mantap
- mantap
- mantap

====================================================================================================
Topic 4

- error mulu
- error mulu
- error mulu

====================================================================================================
Topic 5

- aplikasi menyusahkan
- aplikasi menyusahkan
- aplikasi menyusahkan

====================================================================================================
Topic 6

- sangat bagus
- sangat bagus
- sangat bagus

====================================================================================================
Topic 7

- jelek
- jelek
- jelek

====================================================================================================
Topic 8

- oke
- oke
- oke

====================================================================================================
Topic 9

- good
- good
- good

====================================================================================================
Topic 10

- lumayan
- lumayan
- lumayan

====================================================================================================
Topic 11

- keseringan update
- keseringan update
- keseringan update aplikasi

====================================================================================================
Topic 12

- sangat baik
- sangat baik
- sangat baik

====================================================================================================
Topic 13

- sangat memuaskan
- sangat memuaskan
- sangat memuaskan

====================================================================================================
Topic 14

- baik
- baik
- baik

====================================================================================================
Topic 15

- susah login keterangan unable tapi authenticate your identity kenapa ya
- kenapa bca mobile unable tapi authenticate your identity ya sekarang
- kenapa ada tulisan unable tapi authenticate your identity

====================================================================================================
Topic 16

- ribet
- ribet
- ribet

====================================================================================================
Topic 17

- buruk
- buruk
- buruk

====================================================================================================
Topic 18

- sering keluar sendiri
- sering keluar sendiri
- sering keluar sendiri

====================================================================================================
Topic 19

- payah
- payah
- payah

====================================================================================================
Topic 20

- sangat membantu
- sangat membantu
- sangat membantu

====================================================================================================
Topic 21

- ribet
- ribet
- ribet

====================================================================================================
Topic 22

- susah di buka
- susah di buka
- susah di buka

====================================================================================================
Topic 23

- sangat bermanfaat
- sangat bermanfaat
- sangat bermanfaat

====================================================================================================
Topic 24

- sangat sangat mengecewakan
- sangat sangat mengecewakan
- sangat sangat mengecewakan

====================================================================================================
Topic 25

- mntap
- mntap
- mntap

====================================================================================================
Topic 26

- baik
- baik
- baik

====================================================================================================
Topic 27

- suka eror
- suka eror
- suka eror

====================================================================================================
Topic 28

- mantap
- mantap
- mantap

====================================================================================================
Topic 29

- lelet
- lelet
- lelet

====================================================================================================
Topic 30

- error
- error
- error

====================================================================================================
Topic 31

- keseringan eror
- keseringan eror
- keseringan eror

====================================================================================================
Topic 32

- terbaik
- terbaik
- terbaik

====================================================================================================
Topic 33

- baik
- baik
- baik

====================================================================================================
Topic 34

- apk tolol
- apk tolol
- apk tolol

====================================================================================================
Topic 35

- keren
- keren
- keren

====================================================================================================
Topic 36

- ruwet
- ruwet
- ruwet

====================================================================================================
Topic 37

- gangguan mulu
- gangguan mulu
- gangguan mulu

====================================================================================================
Topic 38

- force close
- force close
- force close

====================================================================================================
Topic 39

- ribet
- ribet
- ribet

====================================================================================================
Topic 40

- sangat membantu
- sangat membantu
- sangat membantu

====================================================================================================
Topic 41

- sering trouble
- sering trouble
- sering trouble

====================================================================================================
Topic 42

- buruk
- buruk
- buruk

====================================================================================================
Topic 43

- aplikasi sampah
- aplikasi sampah
- aplikasi sampah

====================================================================================================
Topic 44

- aplikasi jelek
- aplikasi jelek
- aplikasi jelek

====================================================================================================
Topic 45

- kebanyakan gangguan
- kebanyakan gangguan
- kebanyakan gangguan

====================================================================================================
Topic 46

- aplikasi tolol
- aplikasi tolol
- aplikasi tolol

====================================================================================================
Topic 47

- cukup baik
- cukup baik
- cukup baik

====================================================================================================
Topic 48

- aplikasi buruk
- aplikasi buruk
- aplikasi buruk

====================================================================================================
Topic 49

- sampah
- sampah
- sampah

====================================================================================================
Topic 50

- lambat
- lambat
- lambat

====================================================================================================
Topic 51

- sering bermasalah
- sering bermasalah
- sering bermasalah

====================================================================================================
Topic 52

- nol privasi
- nol privasi
- nol privasi

====================================================================================================
Topic 53

- sering eror
- sering eror
- sering eror

====================================================================================================
Topic 54

- sangat buruk
- sangat buruk
- sangat buruk

====================================================================================================
Topic 55

- cepat dan mudah
- cepat dan mudah
- mudah dan cepat

====================================================================================================
Topic 56

- mengecewakan
- mengecewakan
- mengecewakan

====================================================================================================
Topic 57

- sangat puas
- sangat puas
- sangat puas

====================================================================================================
Topic 58

- sangat membantu
- sangat membantu
- sangat membantu

====================================================================================================
Topic 59

- tidak bisa terbuka
- tidak bisa terbuka
- tidak bisa terbuka

silhoutte score

In [48]:
from sklearn.metrics import silhouette_score

mask = np.array(topics) != -1

silhouette = silhouette_score(
    topic_model.umap_model.embedding_[mask],
    np.array(topics)[mask]
)

print(f"Silhouette Score : {silhouette:.4f}")

Silhouette Score : 0.2514