In [1]:
import pandas as pd
import re
import string
import unicodedata
import emoji

pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv("data/EDA_dataset.csv")
df.head()

,reviewId,content,score,time,bank,year
0,e17751da-bf2e-4a8f-a5a8-334206bb93ca,"ribet banget ni apk sumpah dikir' verif dikit' verif udhmah nyedot pulsa mulu, tolong benerin lah, jangan ribet gini mau pake aja ribet cuh",1,2025-12-31 23:57:59,BCAMOBILE_REVIEWS,2025
1,3481f1d1-a22f-445f-ae2f-ed8c2c9dca53,kenapa QRis ga bisa di pakai ya?? daritadi loading mulu. transfer uang juga gabisa,2,2025-12-31 23:22:32,BCAMOBILE_REVIEWS,2025
2,af69ec6d-cc97-404e-b86a-e5f5b5f1f711,"aplikasi nya sampah, kenapa tiba-tiba keluar terus registrasi ulang lagi, harus pake SMS pulsa pula, sangat tidak membantu ,delete",1,2025-12-31 23:06:58,BCAMOBILE_REVIEWS,2025
3,32d28ac6-c538-4749-969f-8af060915d96,bagus,3,2025-12-31 21:47:45,BCAMOBILE_REVIEWS,2025
4,f99259b7-0d45-4422-b667-6c4fd521638b,tidak ada solusi ketika ada kendala di persulit di lempar kesana kesini sangat mengecewakan harusnya respon dan solusi yang di berikan,1,2025-12-31 21:18:21,BCAMOBILE_REVIEWS,2025

empty review removal

In [3]:
print(f"Before : {len(df):,}")

df = df[
    df["content"]
    .fillna("")
    .str.strip()
    .ne("")
].copy()

print(f"After  : {len(df):,}")

Before : 194,009
After  : 194,009

Noise Review Detection (Inspection Only)

In [4]:
noise_pattern = r"^[A-Za-z\s.,!?;:'\"()\-/\\]+$"

potential_noise = df[
    df["content"]
    .str.fullmatch(noise_pattern, na=False)
]

potential_noise.sample(20, random_state=42)

,reviewId,content,score,time,bank,year
68371,7a39e0a7-eeec-423f-a6ef-0542c6154cb7,Habis update ga bisa di pake,1,2024-08-01 10:07:51,BRIMO_REVIEWS,2024
81087,631dbb83-595c-4361-a622-bd42da67a795,"Bukti transaksi untuk tranfer bank tidak nyaman, lebih suka yang dulu.",2,2023-11-27 14:22:53,BRIMO_REVIEWS,2023
93513,6499d64c-423b-4d99-807f-3ca0f28e1d26,Sering banget erorr nih Kya sekarang manah lgh penting lgh,2,2023-07-01 11:44:15,BRIMO_REVIEWS,2023
17554,6e030d33-5d55-4bcb-8321-43d5473b2f65,"Kembalikan fitur hapus tf, penuh memori ku",3,2024-07-25 10:33:50,BCAMOBILE_REVIEWS,2024
181763,8321da1b-e1d3-4926-bd15-e132b8f4ef57,sering lemot,3,2025-06-28 08:02:43,WONDR_BNI_REVIEWS,2025
172406,592b2101-7e99-4356-97ed-9d8c08fcceea,"Ini aplikasi dikit"" bermasalah terus nggk bisa tranfer lah buat aplikasi yg bener dong",1,2023-01-05 15:57:15,LIVIN_MANDIRI_REVIEWS,2023
180232,ff467f0b-ecea-43f7-961f-e023b35c4ad8,tiap saya mau aktifin biometrik gak bisa terus malah keluar,1,2025-08-01 10:10:07,WONDR_BNI_REVIEWS,2025
57963,e4460482-92e7-42b5-9fd5-2e2a7a1cc076,"Pake brimo baru beberapa bulan sudah harus update,misal hp yang minim ram nya , gimana solusinya agar brimo bisa terpakai",3,2025-01-13 03:34:55,BRIMO_REVIEWS,2025
119630,e3baf39d-f4af-4d52-9ef7-c504aa36f7a1,Kenapa tidak bisaaaaa di donlodddd,2,2025-05-16 14:10:46,LIVIN_MANDIRI_REVIEWS,2025
139036,5e4791b4-9cc1-492c-93ab-93eb68a6f7a0,Saya tidak bisa update selalu gagal terus,1,2024-03-28 10:52:53,LIVIN_MANDIRI_REVIEWS,2024
42036,a8e2cf20-aeac-444d-b162-5a4a214b1f2e,login ribet,1,2025-10-02 15:27:14,BRIMO_REVIEWS,2025
72882,5bd0c045-c95c-4cc2-9c02-78b3220ac902,"Belum kebuka, ferifikasi wajah gagal terus,, padahal udah dicoba berkali kali..",3,2024-04-22 22:35:23,BRIMO_REVIEWS,2024
45948,465fe5ed-f4b8-4484-b94d-bbb9427fa0f1,sangat membantu,1,2025-08-13 14:46:16,BRIMO_REVIEWS,2025
14036,946f167f-c551-4198-b034-cfdc19acf3c4,"Kartu Atm saya, belum bisa digunakan, aplikasi force stop dari tadi. Ko gini?hari Sabtu lagi, ga bisa ke bank langsung kan! rese bgt!!!",2,2024-10-19 14:05:43,BCAMOBILE_REVIEWS,2024
28049,24cebf77-acdc-48b7-9f05-d0ba6c569942,Kebanyakan update makin jelek,1,2023-09-10 02:18:43,BCAMOBILE_REVIEWS,2023
82830,c84016af-ad20-483e-909e-c9112a343454,"Brimo di update malah tambah hancur. IT tolol di pekerjakan, buang aja itu.",1,2023-11-05 00:50:42,BRIMO_REVIEWS,2023
156824,c4212fde-37d2-47be-8d07-90418ba48144,"awal buka aplikasi terlalu lama,mohon diperbaiki",3,2023-07-25 18:01:41,LIVIN_MANDIRI_REVIEWS,2023
93577,aeec6599-30b2-4cba-969e-6dbf4bd07691,Gangguan Mulu brimo,3,2023-07-01 11:30:00,BRIMO_REVIEWS,2023
148392,6099eb2b-0391-45be-834d-0cefd09953b4,Dikit dikit update terus.,3,2023-11-20 18:14:33,LIVIN_MANDIRI_REVIEWS,2023
157264,0f02e16c-0cac-4291-87c9-1924995ee3ce,Aplikasi gak guna banget,1,2023-07-14 05:56:54,LIVIN_MANDIRI_REVIEWS,2023

that weird reviews in eda phase isn't here, weird.

case folding

In [5]:
df["case_folding"] = (
    df["content"]
    .astype(str)
    .str.lower()
)

df[
    ["content", "case_folding"]
].head(10)

,content,case_folding
0,"ribet banget ni apk sumpah dikir' verif dikit' verif udhmah nyedot pulsa mulu, tolong benerin lah, jangan ribet gini mau pake aja ribet cuh","ribet banget ni apk sumpah dikir' verif dikit' verif udhmah nyedot pulsa mulu, tolong benerin lah, jangan ribet gini mau pake aja ribet cuh"
1,kenapa QRis ga bisa di pakai ya?? daritadi loading mulu. transfer uang juga gabisa,kenapa qris ga bisa di pakai ya?? daritadi loading mulu. transfer uang juga gabisa
2,"aplikasi nya sampah, kenapa tiba-tiba keluar terus registrasi ulang lagi, harus pake SMS pulsa pula, sangat tidak membantu ,delete","aplikasi nya sampah, kenapa tiba-tiba keluar terus registrasi ulang lagi, harus pake sms pulsa pula, sangat tidak membantu ,delete"
3,bagus,bagus
4,tidak ada solusi ketika ada kendala di persulit di lempar kesana kesini sangat mengecewakan harusnya respon dan solusi yang di berikan,tidak ada solusi ketika ada kendala di persulit di lempar kesana kesini sangat mengecewakan harusnya respon dan solusi yang di berikan
5,masa gue setiap isi Flazz selalu gagal tapi kedebit gak layak bgt gue ini transaksi ke 4 gue!,masa gue setiap isi flazz selalu gagal tapi kedebit gak layak bgt gue ini transaksi ke 4 gue!
6,Mau Aktifasi di Handphone baru semakin ribet dan sulit tidak seperti yang lalu,mau aktifasi di handphone baru semakin ribet dan sulit tidak seperti yang lalu
7,"sinyal penuh, internet lancar tapi masih aj kode merah... aneh bener","sinyal penuh, internet lancar tapi masih aj kode merah... aneh bener"
8,sinyal bagus tetap biru terus..membuat lama pembayaran,sinyal bagus tetap biru terus..membuat lama pembayaran
9,saya mau login menggunakan pulsa kode selalu tidak keluar,saya mau login menggunakan pulsa kode selalu tidak keluar

checking the data first before continuing

In [6]:
df[
    df["case_folding"].str.contains(
        r"http|www\.",
        regex=True,
        na=False
    )
][["content"]]

                                                                                                                                                                                                                                                                                                                content
87544                                                                                                                                       ketika aplikasi keu hapus trus sayah dowload lagih mau masuk lagih susah harus ada https kaya gtuh di suruh liat sms tapi gak bisa masuk masuk sayah gak ngerti ini gimana?
155691  Admin tidak wajar dari Transaksi.. Ada yang tidak tercatat di Sistem (potongan-potongan gak jelas) saya tanyakan ke cs justru tidak mendapat titik terang... JUMLAHNYA GA banyak. Hanya saja kejujuran itulah yang akan saya perjuangkan. Gimana sih informatika tim IT mandiri.. Apakah HTTP KURANG SECURE????

In [7]:
df[
    df["case_folding"].str.contains(
        r"<.*?>",
        regex=True,
        na=False
    )
][["content"]]

Empty DataFrame
Columns: [content]
Index: []

In [8]:
df[
    df["case_folding"].str.contains(
        "@",
        regex=False,
        na=False
    )
][["content"]]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         content
3006                                                                                                                                                                                                                                                  Masa kalah sama bank J@g0 . transaksi gagal otomatis langsung refund detik itu juga padahal bank besar.BCA Transaksi Qris ada kndala saldo sudh terpotong. tapi di merchant belum masuk dan Saldo belum balik lagi . telpon Cs jawabannya slalu sama semua
12589                                                                                                                                                                                                                                                               Makin update makin gk jelas. Keluar sendiri,, mau pakai hp bagus pun sama saja, gk diperbaiki udah 4 hari, memang t@i,, disitu perlu disitu gk bisa,, udah tempat ku gk ada bca. Bukan diperbaiki. Ada 6 hp,, 6 6 hp gk bisa keluar sendiri.
14478                                                                                                                                                                                                                                                                                                 Setelah di-update aplikasinya malah gak bisa digunakan sampai sekarang, sudah mengikuti saran dari admin @HaloBCA tetep gak bisa.. ayolah BCA, banyak yg membutuhkan ini.. sebelumnya aman2 saja padahal 😓
15520   Siang @BCA, Saya mau melakukan transaksi pembayaran Pajak di aplikasi BCA Mobile, hanya muncul fitur PBB saja. Sedangkan fitur Penerimaan Negara tidak ada. Kemudian saya ke CS Bank BCA terdekat, diarahkan untuk Update aplikasi BCA Mobile. Selesai update dan jalankan aplikasi, namun pada saat halaman utama muncul dan hilang. Begitu juga seterusnya. Sudah restart perangkat Handphone. Tidak membantu juga. Sudah uninstall dan install kembali, namun tetap tidak menyelesaikan permasalahan.
15865                                                                                                                                                                                                                                                                                                                                                                                                                                                          Coba lah di kasih menu login biar enak @developer
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ...
183968                                                                                                                                                                                                                                                                                                                                                                                                                                        pas swa poto loading banget gagal mulu padah@l sudah terang cahaya
188033                                                                                                                                                                                                                                                                                                                                                                     Aplikasi aneh, untuk password biasanya ada kode spesial @ ini tidak ada, terus saat login dimintain centang syarat dan ketentuan lagi
191102                                                                                                                                                                                                                                                                                                                                                                                 Kacau nih app Baru instal terus beli token listrik 2 kali nyoba @ Rp 500 rb pesannya transaksi gagal tapi saldo berkurang
191812                                                                                                                                                                                                                                                                                                                                                                      Bikin pasword dengan special karaktet tapi saat diketik tanda !, tanda @, dan beberapa tanda lainnya kaga nongol!! App macem apaan..
193633                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tetap tidak isa scan waj@h

[95 rows x 1 columns]

unicoe normalization  
normalizing weird fonts

In [9]:
def normalize_unicode(text):
    if not isinstance(text, str):
        return text
    return unicodedata.normalize("NFKC", text)

df["unicode_normalized"] = df["case_folding"].apply(normalize_unicode)

unicode_changed = df[
    df["case_folding"] != df["unicode_normalized"]
]

print(f"Total changed rows: {len(unicode_changed):,}")

unicode_changed[
    [
        "case_folding",
        "unicode_normalized"
    ]
].head(10)

Total changed rows: 3,921

,case_folding,unicode_normalized
20,"indikator lampu merah terus , mana sering gitu mulu lagi, setiap mau dipakek kayak gitu mulu, sampai berjam2 pada hak sinyal bagus, apk udah diperbarui. kejadian terus berulang² dan sering","indikator lampu merah terus , mana sering gitu mulu lagi, setiap mau dipakek kayak gitu mulu, sampai berjam2 pada hak sinyal bagus, apk udah diperbarui. kejadian terus berulang2 dan sering"
21,"kenapa yaa tiap mau buat m-bca selalu stuck di pembuatan sandi m-bca, pas klik send tunggu lampu indikator hijau tapi letak indikator lampunya ga ada, udh coba install uninstall, restart hp ttp ga mau, jaringan wifi sama data juga oke ga ada kendala. ulang² trus smpai brp kali isi pulsa. pdhl dri dulu suka bgt pake ni aplikasi krna simpel, ini ke reset karna ganti no hp. tolong dongg solusinya","kenapa yaa tiap mau buat m-bca selalu stuck di pembuatan sandi m-bca, pas klik send tunggu lampu indikator hijau tapi letak indikator lampunya ga ada, udh coba install uninstall, restart hp ttp ga mau, jaringan wifi sama data juga oke ga ada kendala. ulang2 trus smpai brp kali isi pulsa. pdhl dri dulu suka bgt pake ni aplikasi krna simpel, ini ke reset karna ganti no hp. tolong dongg solusinya"
28,semenjak di update jadi lama bgt kalau mau masuk mbanking nya mau bayar² pake qris juga jadi males,semenjak di update jadi lama bgt kalau mau masuk mbanking nya mau bayar2 pake qris juga jadi males
104,"saldo saya tiba² ilang tanpa ada mutasi padahal kemarin baru kepotong bunga 10rb perbulan, apk aneh","saldo saya tiba2 ilang tanpa ada mutasi padahal kemarin baru kepotong bunga 10rb perbulan, apk aneh"
117,"kenapa lemot sekali mau buka apk nya..pdhal jaringan bagus,tpi jaringan terputus terus kira² knpa ya apa lagi eror","kenapa lemot sekali mau buka apk nya..pdhal jaringan bagus,tpi jaringan terputus terus kira2 knpa ya apa lagi eror"
132,tau² oneklik dinonaktifkan aja ngga jelas apa alasannya.masa iya hanya sebulan ngga transaksi langsung diblokir..ngeselin,tau2 oneklik dinonaktifkan aja ngga jelas apa alasannya.masa iya hanya sebulan ngga transaksi langsung diblokir..ngeselin
305,"setelah update sering muncul indikator merah, sebelumnya lancar² saja dan qris loading sangat lama, bahkan sama sekali ga terbuka. mohon diperbaiki.","setelah update sering muncul indikator merah, sebelumnya lancar2 saja dan qris loading sangat lama, bahkan sama sekali ga terbuka. mohon diperbaiki."
341,indikator warna yg mengganggu sinyal ga cocok dikit gabisa dibuat apa² apknya,indikator warna yg mengganggu sinyal ga cocok dikit gabisa dibuat apa2 apknya
407,"kebiasaan kali sering gangguan pas malam minggu,udah gitu lampu indikator merahnya lama lgi anj,sebelum update aja dah mntp,gk usah di-update klw malah nambah masalah,mbankking dipakek cuma buat byr,ngirim scan brcode doang..gk usah diperberat atau nambah² inj itu jnck","kebiasaan kali sering gangguan pas malam minggu,udah gitu lampu indikator merahnya lama lgi anj,sebelum update aja dah mntp,gk usah di-update klw malah nambah masalah,mbankking dipakek cuma buat byr,ngirim scan brcode doang..gk usah diperberat atau nambah2 inj itu jnck"
432,"semenjak update versi terbaru jadi sangat² berat, mau cek saldo aja lama dan melakukan transaksi juga lama.. mohon segera diperbaiki","semenjak update versi terbaru jadi sangat2 berat, mau cek saldo aja lama dan melakukan transaksi juga lama.. mohon segera diperbaiki"

unicode normalization

In [10]:
def normalize_unicode(text):
    if pd.isna(text):
        return text
    return unicodedata.normalize("NFKD", text)

df["unicode_normalized"] = df["case_folding"].apply(normalize_unicode)

In [11]:
unicode_changed = df[
    df["case_folding"] != df["unicode_normalized"]
][["case_folding", "unicode_normalized"]]

print(f"Rows affected: {len(unicode_changed)}")

unicode_changed.head(10)

Rows affected: 4018

,case_folding,unicode_normalized
20,"indikator lampu merah terus , mana sering gitu mulu lagi, setiap mau dipakek kayak gitu mulu, sampai berjam2 pada hak sinyal bagus, apk udah diperbarui. kejadian terus berulang² dan sering","indikator lampu merah terus , mana sering gitu mulu lagi, setiap mau dipakek kayak gitu mulu, sampai berjam2 pada hak sinyal bagus, apk udah diperbarui. kejadian terus berulang2 dan sering"
21,"kenapa yaa tiap mau buat m-bca selalu stuck di pembuatan sandi m-bca, pas klik send tunggu lampu indikator hijau tapi letak indikator lampunya ga ada, udh coba install uninstall, restart hp ttp ga mau, jaringan wifi sama data juga oke ga ada kendala. ulang² trus smpai brp kali isi pulsa. pdhl dri dulu suka bgt pake ni aplikasi krna simpel, ini ke reset karna ganti no hp. tolong dongg solusinya","kenapa yaa tiap mau buat m-bca selalu stuck di pembuatan sandi m-bca, pas klik send tunggu lampu indikator hijau tapi letak indikator lampunya ga ada, udh coba install uninstall, restart hp ttp ga mau, jaringan wifi sama data juga oke ga ada kendala. ulang2 trus smpai brp kali isi pulsa. pdhl dri dulu suka bgt pake ni aplikasi krna simpel, ini ke reset karna ganti no hp. tolong dongg solusinya"
28,semenjak di update jadi lama bgt kalau mau masuk mbanking nya mau bayar² pake qris juga jadi males,semenjak di update jadi lama bgt kalau mau masuk mbanking nya mau bayar2 pake qris juga jadi males
104,"saldo saya tiba² ilang tanpa ada mutasi padahal kemarin baru kepotong bunga 10rb perbulan, apk aneh","saldo saya tiba2 ilang tanpa ada mutasi padahal kemarin baru kepotong bunga 10rb perbulan, apk aneh"
117,"kenapa lemot sekali mau buka apk nya..pdhal jaringan bagus,tpi jaringan terputus terus kira² knpa ya apa lagi eror","kenapa lemot sekali mau buka apk nya..pdhal jaringan bagus,tpi jaringan terputus terus kira2 knpa ya apa lagi eror"
132,tau² oneklik dinonaktifkan aja ngga jelas apa alasannya.masa iya hanya sebulan ngga transaksi langsung diblokir..ngeselin,tau2 oneklik dinonaktifkan aja ngga jelas apa alasannya.masa iya hanya sebulan ngga transaksi langsung diblokir..ngeselin
305,"setelah update sering muncul indikator merah, sebelumnya lancar² saja dan qris loading sangat lama, bahkan sama sekali ga terbuka. mohon diperbaiki.","setelah update sering muncul indikator merah, sebelumnya lancar2 saja dan qris loading sangat lama, bahkan sama sekali ga terbuka. mohon diperbaiki."
341,indikator warna yg mengganggu sinyal ga cocok dikit gabisa dibuat apa² apknya,indikator warna yg mengganggu sinyal ga cocok dikit gabisa dibuat apa2 apknya
407,"kebiasaan kali sering gangguan pas malam minggu,udah gitu lampu indikator merahnya lama lgi anj,sebelum update aja dah mntp,gk usah di-update klw malah nambah masalah,mbankking dipakek cuma buat byr,ngirim scan brcode doang..gk usah diperberat atau nambah² inj itu jnck","kebiasaan kali sering gangguan pas malam minggu,udah gitu lampu indikator merahnya lama lgi anj,sebelum update aja dah mntp,gk usah di-update klw malah nambah masalah,mbankking dipakek cuma buat byr,ngirim scan brcode doang..gk usah diperberat atau nambah2 inj itu jnck"
432,"semenjak update versi terbaru jadi sangat² berat, mau cek saldo aja lama dan melakukan transaksi juga lama.. mohon segera diperbaiki","semenjak update versi terbaru jadi sangat2 berat, mau cek saldo aja lama dan melakukan transaksi juga lama.. mohon segera diperbaiki"

remove emoji

In [12]:
df["remove_emoji"] = (
    df["unicode_normalized"]
    .apply(lambda text: emoji.replace_emoji(text, replace=""))
)

In [13]:
emoji_changed = df[
    df["unicode_normalized"] != df["remove_emoji"]
][["unicode_normalized", "remove_emoji"]]

print(f"Rows affected: {len(emoji_changed)}")

emoji_changed.head(10)

Rows affected: 11097

,unicode_normalized,remove_emoji
54,"yg terupdate tiap login kenapa mesti 2x siih? login pertama setelah input kode akses, pasti auto belum masuk dan harus ulangi ketik lagi barulah bisa masuk. selalu kaya gitu lohh di versi terbaru ini. padahal versi sebelumnya gak pernah gini. normal aja sekali login langsung masuk. mohon penjelasannya min 🙏","yg terupdate tiap login kenapa mesti 2x siih? login pertama setelah input kode akses, pasti auto belum masuk dan harus ulangi ketik lagi barulah bisa masuk. selalu kaya gitu lohh di versi terbaru ini. padahal versi sebelumnya gak pernah gini. normal aja sekali login langsung masuk. mohon penjelasannya min"
75,habia update malah qris nya lola 🤦,habia update malah qris nya lola
85,mohon bertanya min saya pindah kota ke jawa ko mobile bca sya gk bisa di buka suruh masuk nomor kartu atm tidak ada konfirmasi lewat nomor hp min susah mau isi saldo mlhn eror begini min🙇,mohon bertanya min saya pindah kota ke jawa ko mobile bca sya gk bisa di buka suruh masuk nomor kartu atm tidak ada konfirmasi lewat nomor hp min susah mau isi saldo mlhn eror begini min
87,"mau login ke bca mobile susah, sampai harus ber puluh x tetep aj gak bisa padahal pulsa banyak. gak ad sulusi solusi bantuan g7🤨","mau login ke bca mobile susah, sampai harus ber puluh x tetep aj gak bisa padahal pulsa banyak. gak ad sulusi solusi bantuan g7"
114,"registrasi susah. gagal trs, jelek banget bca mobile skrg 👎👎","registrasi susah. gagal trs, jelek banget bca mobile skrg"
138,"kenapa di hp saya tidak bisa di buka , alasan jaringan bermasalah padhal wifi saya bagus mohon di perbaiki jika sudah saya akan ganti ke ⭐5","kenapa di hp saya tidak bisa di buka , alasan jaringan bermasalah padhal wifi saya bagus mohon di perbaiki jika sudah saya akan ganti ke 5"
148,aku gak bisa masuk akun lama aku 😭😖🙏,aku gak bisa masuk akun lama aku
190,bca mobile terblokir tanpa sebab musabab ada kesalahan pin atau apalah. akhirnya ngrepotin nasabah harus antri panjang ke cs💩💩,bca mobile terblokir tanpa sebab musabab ada kesalahan pin atau apalah. akhirnya ngrepotin nasabah harus antri panjang ke cs
198,"keluar"" mlu dh verifikasi mlu sms😠ud verifikasi wajah masi gagal mlu pulsa habis buat verifikasi bca doang","keluar"" mlu dh verifikasi mlu smsud verifikasi wajah masi gagal mlu pulsa habis buat verifikasi bca doang"
213,"mohon maaf ya bintang satu dulu, notifikasi transfer masuk tidak muncul☺","mohon maaf ya bintang satu dulu, notifikasi transfer masuk tidak muncul"

remove "@"

In [14]:
df["remove_at"] = (
    df["remove_emoji"]
    .str.replace("@", "", regex=False)
)

In [15]:
at_changed = df[
    df["remove_emoji"] != df["remove_at"]
][["remove_emoji", "remove_at"]]

print(f"Rows affected: {len(at_changed):,}")

at_changed.head(10)

Rows affected: 95

,remove_emoji,remove_at
3006,masa kalah sama bank j@g0 . transaksi gagal otomatis langsung refund detik itu juga padahal bank besar.bca transaksi qris ada kndala saldo sudh terpotong. tapi di merchant belum masuk dan saldo belum balik lagi . telpon cs jawabannya slalu sama semua,masa kalah sama bank jg0 . transaksi gagal otomatis langsung refund detik itu juga padahal bank besar.bca transaksi qris ada kndala saldo sudh terpotong. tapi di merchant belum masuk dan saldo belum balik lagi . telpon cs jawabannya slalu sama semua
12589,"makin update makin gk jelas. keluar sendiri,, mau pakai hp bagus pun sama saja, gk diperbaiki udah 4 hari, memang t@i,, disitu perlu disitu gk bisa,, udah tempat ku gk ada bca. bukan diperbaiki. ada 6 hp,, 6 6 hp gk bisa keluar sendiri.","makin update makin gk jelas. keluar sendiri,, mau pakai hp bagus pun sama saja, gk diperbaiki udah 4 hari, memang ti,, disitu perlu disitu gk bisa,, udah tempat ku gk ada bca. bukan diperbaiki. ada 6 hp,, 6 6 hp gk bisa keluar sendiri."
14478,"setelah di-update aplikasinya malah gak bisa digunakan sampai sekarang, sudah mengikuti saran dari admin @halobca tetep gak bisa.. ayolah bca, banyak yg membutuhkan ini.. sebelumnya aman2 saja padahal","setelah di-update aplikasinya malah gak bisa digunakan sampai sekarang, sudah mengikuti saran dari admin halobca tetep gak bisa.. ayolah bca, banyak yg membutuhkan ini.. sebelumnya aman2 saja padahal"
15520,"siang @bca, saya mau melakukan transaksi pembayaran pajak di aplikasi bca mobile, hanya muncul fitur pbb saja. sedangkan fitur penerimaan negara tidak ada. kemudian saya ke cs bank bca terdekat, diarahkan untuk update aplikasi bca mobile. selesai update dan jalankan aplikasi, namun pada saat halaman utama muncul dan hilang. begitu juga seterusnya. sudah restart perangkat handphone. tidak membantu juga. sudah uninstall dan install kembali, namun tetap tidak menyelesaikan permasalahan.","siang bca, saya mau melakukan transaksi pembayaran pajak di aplikasi bca mobile, hanya muncul fitur pbb saja. sedangkan fitur penerimaan negara tidak ada. kemudian saya ke cs bank bca terdekat, diarahkan untuk update aplikasi bca mobile. selesai update dan jalankan aplikasi, namun pada saat halaman utama muncul dan hilang. begitu juga seterusnya. sudah restart perangkat handphone. tidak membantu juga. sudah uninstall dan install kembali, namun tetap tidak menyelesaikan permasalahan."
15865,coba lah di kasih menu login biar enak @developer,coba lah di kasih menu login biar enak developer
20917,proses verifikasi sangat ribet sekali sudah berulangkali dicoba tetap gagal terus..kirim sms terus ngulang berkali-kali..gini mau online pengennya cepet kok tambah dibuat susah.. beda sama aplikasi mobile bank m@nd##i sebelah lebih simple sat set langsung beres.. itnya bca gimana ni bikin aplikasi perlu ditingkatkan lagi ni..,proses verifikasi sangat ribet sekali sudah berulangkali dicoba tetap gagal terus..kirim sms terus ngulang berkali-kali..gini mau online pengennya cepet kok tambah dibuat susah.. beda sama aplikasi mobile bank mnd##i sebelah lebih simple sat set langsung beres.. itnya bca gimana ni bikin aplikasi perlu ditingkatkan lagi ni..
22596,aplikasi apa ni .. bca bank besar login aja susah... mau top up mssih jaman majapahit pake kode2@n ... dih klaah ama bamk lain bro,aplikasi apa ni .. bca bank besar login aja susah... mau top up mssih jaman majapahit pake kode2n ... dih klaah ama bamk lain bro
24547,aa5ze×an3@ gbbi,aa5ze×an3 gbbi
29267,"gaji gw belum di bayar sampe sekarang,padahal tiap tanggal 27,@pt.andalan artha l.jakarta pusat?","gaji gw belum di bayar sampe sekarang,padahal tiap tanggal 27,pt.andalan artha l.jakarta pusat?"
32752,"dari segi tampilan dan kegunaannya tidak pernah di update terkini, contoh liv*n m@nd*ri fitur nya keren","dari segi tampilan dan kegunaannya tidak pernah di update terkini, contoh liv*n mnd*ri fitur nya keren"

remove punctuation

In [16]:
df["remove_punctuation"] = (
    df["remove_at"]
    .str.replace(r"[^\w\s]", " ", regex=True)
)

In [17]:
punctuation_changed = df[
    df["remove_at"] != df["remove_punctuation"]
][["remove_at", "remove_punctuation"]]

print(f"Rows affected: {len(punctuation_changed):,}")

punctuation_changed.head(10)

Rows affected: 123,575

,remove_at,remove_punctuation
0,"ribet banget ni apk sumpah dikir' verif dikit' verif udhmah nyedot pulsa mulu, tolong benerin lah, jangan ribet gini mau pake aja ribet cuh",ribet banget ni apk sumpah dikir verif dikit verif udhmah nyedot pulsa mulu tolong benerin lah jangan ribet gini mau pake aja ribet cuh
1,kenapa qris ga bisa di pakai ya?? daritadi loading mulu. transfer uang juga gabisa,kenapa qris ga bisa di pakai ya daritadi loading mulu transfer uang juga gabisa
2,"aplikasi nya sampah, kenapa tiba-tiba keluar terus registrasi ulang lagi, harus pake sms pulsa pula, sangat tidak membantu ,delete",aplikasi nya sampah kenapa tiba tiba keluar terus registrasi ulang lagi harus pake sms pulsa pula sangat tidak membantu delete
5,masa gue setiap isi flazz selalu gagal tapi kedebit gak layak bgt gue ini transaksi ke 4 gue!,masa gue setiap isi flazz selalu gagal tapi kedebit gak layak bgt gue ini transaksi ke 4 gue
7,"sinyal penuh, internet lancar tapi masih aj kode merah... aneh bener",sinyal penuh internet lancar tapi masih aj kode merah aneh bener
8,sinyal bagus tetap biru terus..membuat lama pembayaran,sinyal bagus tetap biru terus membuat lama pembayaran
11,"kenapa setelah masuk ke mbanking, harus aktivasi ulang ke cs buat transaksi finansialnya. padahal sebelumnya pernah aktif di hp yg sama. ribet banget tau gak sih!",kenapa setelah masuk ke mbanking harus aktivasi ulang ke cs buat transaksi finansialnya padahal sebelumnya pernah aktif di hp yg sama ribet banget tau gak sih
12,"kasik bintang 1 dulu aku new user bca, saldoku 96k pas di cek lagi kok berkurang jadi 71k ya? terus notif transaksi jga lambat, gaada catatan transaksi jga tolong dong di perbaiki. kalau udh dibalas nanti aku tambahin 1 bintang lagi",kasik bintang 1 dulu aku new user bca saldoku 96k pas di cek lagi kok berkurang jadi 71k ya terus notif transaksi jga lambat gaada catatan transaksi jga tolong dong di perbaiki kalau udh dibalas nanti aku tambahin 1 bintang lagi
14,tiap verifikasi wajah knapa slalu gagal. ganti hp karna hp lama udah eror. malah pas mau log in ke bca susah bgt. tiap verifikasi gagal terus. padahal pencahayaan udah aman.tolong bantuan dan sarqnnya dong,tiap verifikasi wajah knapa slalu gagal ganti hp karna hp lama udah eror malah pas mau log in ke bca susah bgt tiap verifikasi gagal terus padahal pencahayaan udah aman tolong bantuan dan sarqnnya dong
17,apa ini aplikasi bintang 1.. register mobile banking dari pagi ampe sore bilangnya tunggu indikator hijau... pdahal tidak ada indikator sama sekali ampe habis pulsa gue 20k,apa ini aplikasi bintang 1 register mobile banking dari pagi ampe sore bilangnya tunggu indikator hijau pdahal tidak ada indikator sama sekali ampe habis pulsa gue 20k

remove extra whitespace

In [18]:
df["cleaned"] = (
    df["remove_punctuation"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [19]:
space_changed = df[
    df["remove_punctuation"] != df["cleaned"]
][["remove_punctuation", "cleaned"]]

print(f"Rows affected: {len(space_changed):,}")

space_changed.head(10)

Rows affected: 116,568

,remove_punctuation,cleaned
0,ribet banget ni apk sumpah dikir verif dikit verif udhmah nyedot pulsa mulu tolong benerin lah jangan ribet gini mau pake aja ribet cuh,ribet banget ni apk sumpah dikir verif dikit verif udhmah nyedot pulsa mulu tolong benerin lah jangan ribet gini mau pake aja ribet cuh
1,kenapa qris ga bisa di pakai ya daritadi loading mulu transfer uang juga gabisa,kenapa qris ga bisa di pakai ya daritadi loading mulu transfer uang juga gabisa
2,aplikasi nya sampah kenapa tiba tiba keluar terus registrasi ulang lagi harus pake sms pulsa pula sangat tidak membantu delete,aplikasi nya sampah kenapa tiba tiba keluar terus registrasi ulang lagi harus pake sms pulsa pula sangat tidak membantu delete
5,masa gue setiap isi flazz selalu gagal tapi kedebit gak layak bgt gue ini transaksi ke 4 gue,masa gue setiap isi flazz selalu gagal tapi kedebit gak layak bgt gue ini transaksi ke 4 gue
7,sinyal penuh internet lancar tapi masih aj kode merah aneh bener,sinyal penuh internet lancar tapi masih aj kode merah aneh bener
8,sinyal bagus tetap biru terus membuat lama pembayaran,sinyal bagus tetap biru terus membuat lama pembayaran
11,kenapa setelah masuk ke mbanking harus aktivasi ulang ke cs buat transaksi finansialnya padahal sebelumnya pernah aktif di hp yg sama ribet banget tau gak sih,kenapa setelah masuk ke mbanking harus aktivasi ulang ke cs buat transaksi finansialnya padahal sebelumnya pernah aktif di hp yg sama ribet banget tau gak sih
12,kasik bintang 1 dulu aku new user bca saldoku 96k pas di cek lagi kok berkurang jadi 71k ya terus notif transaksi jga lambat gaada catatan transaksi jga tolong dong di perbaiki kalau udh dibalas nanti aku tambahin 1 bintang lagi,kasik bintang 1 dulu aku new user bca saldoku 96k pas di cek lagi kok berkurang jadi 71k ya terus notif transaksi jga lambat gaada catatan transaksi jga tolong dong di perbaiki kalau udh dibalas nanti aku tambahin 1 bintang lagi
14,tiap verifikasi wajah knapa slalu gagal ganti hp karna hp lama udah eror malah pas mau log in ke bca susah bgt tiap verifikasi gagal terus padahal pencahayaan udah aman tolong bantuan dan sarqnnya dong,tiap verifikasi wajah knapa slalu gagal ganti hp karna hp lama udah eror malah pas mau log in ke bca susah bgt tiap verifikasi gagal terus padahal pencahayaan udah aman tolong bantuan dan sarqnnya dong
17,apa ini aplikasi bintang 1 register mobile banking dari pagi ampe sore bilangnya tunggu indikator hijau pdahal tidak ada indikator sama sekali ampe habis pulsa gue 20k,apa ini aplikasi bintang 1 register mobile banking dari pagi ampe sore bilangnya tunggu indikator hijau pdahal tidak ada indikator sama sekali ampe habis pulsa gue 20k

remove empty reviews

In [20]:
before = len(df)

df = df[
    df["cleaned"]
    .str.strip()
    .ne("")
].copy()

after = len(df)

print(f"Before : {before:,}")
print(f"After  : {after:,}")
print(f"Removed: {before-after:,}")

Before : 194,009
After  : 193,827
Removed: 182

final comparison

In [21]:
comparison = df.copy()

comparison["changes"] = (
    (comparison["content"] != comparison["case_folding"]).astype(int) +
    (comparison["case_folding"] != comparison["unicode_normalized"]).astype(int) +
    (comparison["unicode_normalized"] != comparison["remove_emoji"]).astype(int) +
    (comparison["remove_emoji"] != comparison["remove_at"]).astype(int) +
    (comparison["remove_at"] != comparison["remove_punctuation"]).astype(int) +
    (comparison["remove_punctuation"] != comparison["cleaned"]).astype(int)
)

comparison = comparison.sort_values(
    by="changes",
    ascending=False
)

comparison[
    [
        "changes",
        "content",
        "case_folding",
        "unicode_normalized",
        "remove_emoji",
        "remove_at",
        "remove_punctuation",
        "cleaned"
    ]
].head(10)

,changes,content,case_folding,unicode_normalized,remove_emoji,remove_at,remove_punctuation,cleaned
67671,5,Apasih aplikasi makin gajelas. Yakali tiap bulan ada mutasi dg nominal 350rb yg bahkan gapernah gw inget atau melakukan transaksi segitu buat apaan. Tgl 9-8 ini cnthnya. Seharian full ga pegang hp. Malemnya kelar acara tiba² liat mutasi ada keluar duid 350rb. Woiii yg bnr aja komcol. Mendingam gw pindah ke BCA kocak🤬🤬🤬🤬,apasih aplikasi makin gajelas. yakali tiap bulan ada mutasi dg nominal 350rb yg bahkan gapernah gw inget atau melakukan transaksi segitu buat apaan. tgl 9-8 ini cnthnya. seharian full ga pegang hp. malemnya kelar acara tiba² liat mutasi ada keluar duid 350rb. woiii yg bnr aja komcol. mendingam gw pindah ke bca kocak🤬🤬🤬🤬,apasih aplikasi makin gajelas. yakali tiap bulan ada mutasi dg nominal 350rb yg bahkan gapernah gw inget atau melakukan transaksi segitu buat apaan. tgl 9-8 ini cnthnya. seharian full ga pegang hp. malemnya kelar acara tiba2 liat mutasi ada keluar duid 350rb. woiii yg bnr aja komcol. mendingam gw pindah ke bca kocak🤬🤬🤬🤬,apasih aplikasi makin gajelas. yakali tiap bulan ada mutasi dg nominal 350rb yg bahkan gapernah gw inget atau melakukan transaksi segitu buat apaan. tgl 9-8 ini cnthnya. seharian full ga pegang hp. malemnya kelar acara tiba2 liat mutasi ada keluar duid 350rb. woiii yg bnr aja komcol. mendingam gw pindah ke bca kocak,apasih aplikasi makin gajelas. yakali tiap bulan ada mutasi dg nominal 350rb yg bahkan gapernah gw inget atau melakukan transaksi segitu buat apaan. tgl 9-8 ini cnthnya. seharian full ga pegang hp. malemnya kelar acara tiba2 liat mutasi ada keluar duid 350rb. woiii yg bnr aja komcol. mendingam gw pindah ke bca kocak,apasih aplikasi makin gajelas yakali tiap bulan ada mutasi dg nominal 350rb yg bahkan gapernah gw inget atau melakukan transaksi segitu buat apaan tgl 9 8 ini cnthnya seharian full ga pegang hp malemnya kelar acara tiba2 liat mutasi ada keluar duid 350rb woiii yg bnr aja komcol mendingam gw pindah ke bca kocak,apasih aplikasi makin gajelas yakali tiap bulan ada mutasi dg nominal 350rb yg bahkan gapernah gw inget atau melakukan transaksi segitu buat apaan tgl 9 8 ini cnthnya seharian full ga pegang hp malemnya kelar acara tiba2 liat mutasi ada keluar duid 350rb woiii yg bnr aja komcol mendingam gw pindah ke bca kocak
116587,5,"Semakin ribet aja nc Livin mandiri...!! Gara² menghapus chace d apk lalu mau masuk d suruh verifikasi wajah lagi...!! Dah lh hp jadul camera pun blur....!! Gx kayak Bank lain,,gx harus pakai verifikasi wajah...!! 😠😠","semakin ribet aja nc livin mandiri...!! gara² menghapus chace d apk lalu mau masuk d suruh verifikasi wajah lagi...!! dah lh hp jadul camera pun blur....!! gx kayak bank lain,,gx harus pakai verifikasi wajah...!! 😠😠","semakin ribet aja nc livin mandiri...!! gara2 menghapus chace d apk lalu mau masuk d suruh verifikasi wajah lagi...!! dah lh hp jadul camera pun blur....!! gx kayak bank lain,,gx harus pakai verifikasi wajah...!! 😠😠","semakin ribet aja nc livin mandiri...!! gara2 menghapus chace d apk lalu mau masuk d suruh verifikasi wajah lagi...!! dah lh hp jadul camera pun blur....!! gx kayak bank lain,,gx harus pakai verifikasi wajah...!!","semakin ribet aja nc livin mandiri...!! gara2 menghapus chace d apk lalu mau masuk d suruh verifikasi wajah lagi...!! dah lh hp jadul camera pun blur....!! gx kayak bank lain,,gx harus pakai verifikasi wajah...!!",semakin ribet aja nc livin mandiri gara2 menghapus chace d apk lalu mau masuk d suruh verifikasi wajah lagi dah lh hp jadul camera pun blur gx kayak bank lain gx harus pakai verifikasi wajah,semakin ribet aja nc livin mandiri gara2 menghapus chace d apk lalu mau masuk d suruh verifikasi wajah lagi dah lh hp jadul camera pun blur gx kayak bank lain gx harus pakai verifikasi wajah
71939,5,"Sulit dalam pengajuan untuk melakukan pinjaman di aplikasi Brimo Selalu 'Maaf Sistem kami sedang tidak dapat dijangkau"" Tapi WhatsApp slalu masuk pesan ajukan segera pinjamanMu. Kecewa Lama² gue gamau makek ini aplikasi😑","sulit dalam pengajuan untuk melakukan pinjaman di aplikasi brimo selalu 'maaf sistem kami sedang tidak dapat dijangkau"" tapi whatsapp slalu masuk pesan ajukan segera pinjamanmu. kecewa lama² gue gamau makek ini aplikasi😑","sulit dalam pengajuan untuk melakukan pinjaman di aplikasi brimo selalu 'maaf sistem kami sedang tidak dapat dijangkau"" tapi whatsapp slalu masuk pesan ajukan segera pinjamanmu. kecewa lama2 gue gamau makek ini aplikasi😑","sulit dalam pengajuan untuk melakukan pinjaman di aplikasi brimo selalu 'maaf sistem kami sedang tidak dapat dijangkau"" tapi whatsapp slalu masuk pesan ajukan segera pinjamanmu. kecewa lama2 gue gamau makek ini aplikasi","sulit dalam pengajuan untuk melakukan pinjaman di aplikasi brimo selalu 'maaf sistem kami sedang tidak dapat dijangkau"" tapi whatsapp slalu masuk pesan ajukan segera pinjamanmu. kecewa lama2 gue gamau makek ini aplikasi",sulit dalam pengajuan untuk melakukan pinjaman di aplikasi brimo selalu maaf sistem kami sedang tidak dapat dijangkau tapi whatsapp slalu masuk pesan ajukan segera pinjamanmu kecewa lama2 gue gamau makek ini aplikasi,sulit dalam pengajuan untuk melakukan pinjaman di aplikasi brimo selalu maaf sistem kami sedang tidak dapat dijangkau tapi whatsapp slalu masuk pesan ajukan segera pinjamanmu kecewa lama2 gue gamau makek ini aplikasi
110517,5,"lagi jalan² ke mall ,ga bawa kartu atm biasanya Qris aja bs, ehhh gangguan ga bawa uang cash ya Allah nyesekkk x😭😭😭","lagi jalan² ke mall ,ga bawa kartu atm biasanya qris aja bs, ehhh gangguan ga bawa uang cash ya allah nyesekkk x😭😭😭","lagi jalan2 ke mall ,ga bawa kartu atm biasanya qris aja bs, ehhh gangguan ga bawa uang cash ya allah nyesekkk x😭😭😭","lagi jalan2 ke mall ,ga bawa kartu atm biasanya qris aja bs, ehhh gangguan ga bawa uang cash ya allah nyesekkk x","lagi jalan2 ke mall ,ga bawa kartu atm biasanya qris aja bs, ehhh gangguan ga bawa uang cash ya allah nyesekkk x",lagi jalan2 ke mall ga bawa kartu atm biasanya qris aja bs ehhh gangguan ga bawa uang cash ya allah nyesekkk x,lagi jalan2 ke mall ga bawa kartu atm biasanya qris aja bs ehhh gangguan ga bawa uang cash ya allah nyesekkk x
98235,5,"Hati hati dengan bank BRI terlalu banyak embel²nya sistemnya kurang aman, uang tabungan saya 20jt lebih hilang, pihak bank ga mau tanggung jawab, cuman ngajak debat doang🤬🥵🥵😭","hati hati dengan bank bri terlalu banyak embel²nya sistemnya kurang aman, uang tabungan saya 20jt lebih hilang, pihak bank ga mau tanggung jawab, cuman ngajak debat doang🤬🥵🥵😭","hati hati dengan bank bri terlalu banyak embel2nya sistemnya kurang aman, uang tabungan saya 20jt lebih hilang, pihak bank ga mau tanggung jawab, cuman ngajak debat doang🤬🥵🥵😭","hati hati dengan bank bri terlalu banyak embel2nya sistemnya kurang aman, uang tabungan saya 20jt lebih hilang, pihak bank ga mau tanggung jawab, cuman ngajak debat doang","hati hati dengan bank bri terlalu banyak embel2nya sistemnya kurang aman, uang tabungan saya 20jt lebih hilang, pihak bank ga mau tanggung jawab, cuman ngajak debat doang",hati hati dengan bank bri terlalu banyak embel2nya sistemnya kurang aman uang tabungan saya 20jt lebih hilang pihak bank ga mau tanggung jawab cuman ngajak debat doang,hati hati dengan bank bri terlalu banyak embel2nya sistemnya kurang aman uang tabungan saya 20jt lebih hilang pihak bank ga mau tanggung jawab cuman ngajak debat doang
100471,5,"Verifikasi wajah bolak balik udh sesuai petunjuk masih aja gagal,, bangkee,, bintang 1 gini aja g ikhlas bangat.. Uninstall akhirnya.. buang² kuota data aja😈😈😈","verifikasi wajah bolak balik udh sesuai petunjuk masih aja gagal,, bangkee,, bintang 1 gini aja g ikhlas bangat.. uninstall akhirnya.. buang² kuota data aja😈😈😈","verifikasi wajah bolak balik udh sesuai petunjuk masih aja gagal,, bangkee,, bintang 1 gini aja g ikhlas bangat.. uninstall akhirnya.. buang2 kuota data aja😈😈😈","verifikasi wajah bolak balik udh sesuai petunjuk masih aja gagal,, bangkee,, bintang 1 gini aja g ikhlas bangat.. uninstall akhirnya.. buang2 kuota data aja","verifikasi wajah bolak balik udh sesuai petunjuk masih aja gagal,, bangkee,, bintang 1 gini aja g ikhlas bangat.. uninstall akhirnya.. buang2 kuota data aja",verifikasi wajah bolak balik udh sesuai petunjuk masih aja gagal bangkee bintang 1 gini aja g ikhlas bangat uninstall akhirnya buang2 kuota data aja,verifikasi wajah bolak balik udh sesuai petunjuk masih aja gagal bangkee bintang 1 gini aja g ikhlas bangat uninstall akhirnya buang2 kuota data aja
67679,5,"Bri² sistem kalian eror semua, login eror di suruh daftar ulang... Gitu aja terus.. Kalian kalah sama BCA sistem sepele login dengan nomor yang di daftar gk bisa wifi gk bisa, masa iya hapus akun, hapus akun.. Daftar lagi daftar lagi.. Mengecewakan, sangat kacau sistem nya kayak kominfo, login eror malah di suruh hapus akun daftar lagi, tanpa KTP enak cepet #repot 😀 bukannya di perbaiki tu sistem nya agar lebih baik, apa mentang² keamanan? Sama aja di kasik apk phishing hilang uang nya!","bri² sistem kalian eror semua, login eror di suruh daftar ulang... gitu aja terus.. kalian kalah sama bca sistem sepele login dengan nomor yang di daftar gk bisa wifi gk bisa, masa iya hapus akun, hapus akun.. daftar lagi daftar lagi.. mengecewakan, sangat kacau sistem nya kayak kominfo, login eror malah di suruh hapus akun daftar lagi, tanpa ktp enak cepet #repot 😀 bukannya di perbaiki tu sistem nya agar lebih baik, apa mentang² keamanan? sama aja di kasik apk phishing hilang uang nya!","bri2 sistem kalian eror semua, login eror di suruh daftar ulang... gitu aja terus.. kalian kalah sama bca sistem sepele login dengan nomor yang di daftar gk bisa wifi gk bisa, masa iya hapus akun, hapus akun.. daftar lagi daftar lagi.. mengecewakan, sangat kacau sistem nya kayak kominfo, login eror malah di suruh hapus akun daftar lagi, tanpa ktp enak cepet #repot 😀 bukannya di perbaiki tu sistem nya agar lebih baik, apa mentang2 keamanan? sama aja di kasik apk phishing hilang uang nya!","bri2 sistem kalian eror semua, login eror di suruh daftar ulang... gitu aja terus.. kalian kalah sama bca sistem sepele login dengan nomor yang di daftar gk bisa wifi gk bisa, masa iya hapus akun, hapus akun.. daftar lagi daftar lagi.. mengecewakan, sangat kacau sistem nya kayak kominfo, login eror malah di suruh hapus akun daftar lagi, tanpa ktp enak cepet #repot bukannya di perbaiki tu sistem nya agar lebih baik, apa mentang2 keamanan? sama aja di kasik apk phishing hilang uang nya!","bri2 sistem kalian eror semua, login eror di suruh daftar ulang... gitu aja terus.. kalian kalah sama bca sistem sepele login dengan nomor yang di daftar gk bisa wifi gk bisa, masa iya hapus akun, hapus akun.. daftar lagi daftar lagi.. mengecewakan, sangat kacau sistem nya kayak kominfo, login eror malah di suruh hapus akun daftar lagi, tanpa ktp enak cepet #repot bukannya di perbaiki tu sistem nya agar lebih baik, apa mentang2 keamanan? sama aja di kasik apk phishing hilang uang nya!",bri2 sistem kalian eror semua login eror di suruh daftar ulang gitu aja terus kalian kalah sama bca sistem sepele login dengan nomor yang di daftar gk bisa wifi gk bisa masa iya hapus akun hapus akun daftar lagi daftar lagi mengecewakan sangat kacau sistem nya kayak kominfo login eror malah di suruh hapus akun daftar lagi tanpa ktp enak cepet repot bukannya di perbaiki tu sistem nya agar lebih baik apa mentang2 keamanan sama aja di kasik apk phishing hilang uang nya,bri2 sistem kalian eror semua login eror di suruh daftar ulang gitu aja terus kalian kalah sama bca sistem sepele login dengan nomor yang di daftar gk bisa wifi gk bisa masa iya hapus akun hapus akun daftar lagi daftar lagi mengecewakan sangat kacau sistem nya kayak kominfo login eror malah di suruh hapus akun daftar lagi tanpa ktp enak cepet repot bukannya di perbaiki tu sistem nya agar lebih baik apa mentang2 keamanan sama aja di kasik apk phishing hilang uang nya
96891,5,"Nunggu kode verifikasi ke SMS aja sampe se-abad, nggak muncul², cape gua, perkara pengen ganti password brimo aja di persulit, bank bumn memang nggak ada yg betul. 🥱😴 CS said :""untuk kode verifikasi sms nya silahkan di cek kembali jaringan nya, pastikan nomor anda aktif, pastikan saldo pulsa ada di nomor anda, pastikan nomor anda benar (lah kalau nggak bener kenapa bisa bikin akun brimo?)"", pastikan... pastikan.. dan pastikan, gitu aja terus.","nunggu kode verifikasi ke sms aja sampe se-abad, nggak muncul², cape gua, perkara pengen ganti password brimo aja di persulit, bank bumn memang nggak ada yg betul. 🥱😴 cs said :""untuk kode verifikasi sms nya silahkan di cek kembali jaringan nya, pastikan nomor anda aktif, pastikan saldo pulsa ada di nomor anda, pastikan nomor anda benar (lah kalau nggak bener kenapa bisa bikin akun brimo?)"", pastikan... pastikan.. dan pastikan, gitu aja terus.","nunggu kode verifikasi ke sms aja sampe se-abad, nggak muncul2, cape gua, perkara pengen ganti password brimo aja di persulit, bank bumn memang nggak ada yg betul. 🥱😴 cs said :""untuk kode verifikasi sms nya silahkan di cek kembali jaringan nya, pastikan nomor anda aktif, pastikan saldo pulsa ada di nomor anda, pastikan nomor anda benar (lah kalau nggak bener kenapa bisa bikin akun brimo?)"", pastikan... pastikan.. dan pastikan, gitu aja terus.","nunggu kode verifikasi ke sms aja sampe se-abad, nggak muncul2, cape gua, perkara pengen ganti password brimo aja di persulit, bank bumn memang nggak ada yg betul. cs said :""untuk kode verifikasi sms nya silahkan di cek kembali jaringan nya, pastikan nomor anda aktif, pastikan saldo pulsa ada di nomor anda, pastikan nomor anda benar (lah kalau nggak bener kenapa bisa bikin akun brimo?)"", pastikan... pastikan.. dan pastikan, gitu aja terus.","nunggu kode verifikasi ke sms aja sampe se-abad, nggak muncul2, cape gua, perkara pengen ganti password brimo aja di persulit, bank bumn memang nggak ada yg betul. cs said :""untuk kode verifikasi sms nya silahkan di cek kembali jaringan nya, pastikan nomor anda aktif, pastikan saldo pulsa ada di nomor anda, pastikan nomor anda benar (lah kalau nggak bener kenapa bisa bikin akun brimo?)"", pastikan... pastikan.. dan pastikan, gitu aja terus.",nunggu kode verifikasi ke sms aja sampe se abad nggak muncul2 cape gua perkara pengen ganti password brimo aja di persulit bank bumn memang nggak ada yg betul cs said untuk kode verifikasi sms nya silahkan di cek kembali jaringan nya pastikan nomor anda aktif pastikan saldo pulsa ada di nomor anda pastikan nomor anda benar lah kalau nggak bener kenapa bisa bikin akun brimo pastikan pastikan dan pastikan gitu aja terus,nunggu kode verifikasi ke sms aja sampe se abad nggak muncul2 cape gua perkara pengen ganti password brimo aja di persulit bank bumn memang nggak ada yg betul cs said untuk kode verifikasi sms nya silahkan di cek kembali jaringan nya pastikan nomor anda aktif pastikan saldo pulsa ada di nomor anda pastikan nomor anda benar lah kalau nggak bener kenapa bisa bikin akun brimo pastikan pastikan dan pastikan gitu aja terus
89399,5,"Aplikasi banking paling brengsek & ribet yg pernah gue coba, setiap daftar selalu SIA9 terus, padahal data² sudah sesuai ketika mendaftar di Bank, ANTI-RIBET MATA LU.🖕","aplikasi banking paling brengsek & ribet yg pernah gue coba, setiap daftar selalu sia9 terus, padahal data² sudah sesuai ketika mendaftar di bank, anti-ribet mata lu.🖕","aplikasi banking paling brengsek & ribet yg pernah gue coba, setiap daftar selalu sia9 terus, padahal data2 sudah sesuai ketika mendaftar di bank, anti-ribet mata lu.🖕","aplikasi banking paling brengsek & ribet yg pernah gue coba, setiap daftar selalu sia9 terus, padahal data2 sudah sesuai ketika mendaftar di bank, anti-ribet mata lu.","aplikasi banking paling brengsek & ribet yg pernah gue coba, setiap daftar selalu sia9 terus, padahal data2 sudah sesuai ketika mendaftar di bank, anti-ribet mata lu.",aplikasi banking paling brengsek ribet yg pernah gue coba setiap daftar selalu sia9 terus padahal data2 sudah sesuai ketika mendaftar di bank anti ribet mata lu,aplikasi banking paling brengsek ribet yg pernah gue coba setiap daftar selalu sia9 terus padahal data2 sudah sesuai ketika mendaftar di bank anti ribet mata lu
193167,5,Login sulit bener bagian verifikasi wajah padahal sudah sesuai instruksi malah coba lagi² terus coba lagi besok ya. Apalah 😠,login sulit bener bagian verifikasi wajah padahal sudah sesuai instruksi malah coba lagi² terus coba lagi besok ya. apalah 😠,login sulit bener bagian verifikasi wajah padahal sudah sesuai instruksi malah coba lagi2 terus coba lagi besok ya. apalah 😠,login sulit bener bagian verifikasi wajah padahal sudah sesuai instruksi malah coba lagi2 terus coba lagi besok ya. apalah,login sulit bener bagian verifikasi wajah padahal sudah sesuai instruksi malah coba lagi2 terus coba lagi besok ya. apalah,login sulit bener bagian verifikasi wajah padahal sudah sesuai instruksi malah coba lagi2 terus coba lagi besok ya apalah,login sulit bener bagian verifikasi wajah padahal sudah sesuai instruksi malah coba lagi2 terus coba lagi besok ya apalah

slang words normalization

In [22]:
slang_dict = pd.read_csv("data/colloquial-indonesian-lexicon.csv")

slang_dict = slang_dict[["slang", "formal"]]

print(len(slang_dict))
slang_dict.head(20)

15006

         slang        formal
0         woww           wow
1        aminn          amin
2          met       selamat
3       netaas       menetas
4      keberpa      keberapa
5     eeeehhhh            eh
6   kata2nyaaa  kata-katanya
7        hallo          halo
8         kaka         kakak
9           ka           kak
10        daah           dah
11   aaaaahhhh            ah
12         yaa            ya
13        smga        semoga
14       slalu        selalu
15       amiin          amin
16          kk         kakak
17        trus         terus
18          kk         kakak
19         sii           sih

In [23]:
slang_dict = dict(
    zip(
        slang_dict["slang"],
        slang_dict["formal"]
    )
)

In [24]:
print(slang_dict["blh"])

boleh

In [25]:
protected_words = {
    # Banks
    "bca",
    "bni",
    "bri",
    "mandiri",

    # Applications
    "brimo",
    "livin",
    "wondr",
    "blu",

    # Banking terms
    "qris",
    "qr",
    "atm",
    "otp",
    "pin",
    "rekening",
    "mbanking",
    "mbanking",
    "m-banking",
    "internet",
    "mobile",
    "token",
    "mtoken",

    # Company names
    "dana",
    "ovo",
    "gopay",
    "linkaja",
    "flip",

    # Payment systems
    "visa",
    "mastercard"
}

In [26]:
# from collections import Counter

# all_words = []

# for text in df["cleaned"]:
#     all_words.extend(text.split())

# word_freq = Counter(all_words)

# vocab_df = (
#     pd.DataFrame(
#         word_freq.items(),
#         columns=["word", "frequency"]
#     )
#     .sort_values(
#         by="frequency",
#         ascending=False
#     )
#         .reset_index(drop=True)
# )

In [27]:
# vocab_df["in_dictionary"] = vocab_df["word"].isin(slang_dict)

# vocab_df["formal"] = vocab_df["word"].map(slang_dict)

# vocab_df.head()

In [28]:
# def classify(row):
#     if row["in_dictionary"]:
#         return "Dictionary"

#     if row["frequency"] >= 20:
#         return "Review"

#     return "Rare"

# vocab_df["status"] = vocab_df.apply(classify, axis=1)

In [29]:
# vocab_df = vocab_df.sort_values(
#     by=[
#         "status",
#         "frequency"
#     ],
#     ascending=[True, False]
# )

In [30]:
# vocab_df["approved"] = ""
# vocab_df["notes"] = ""

# vocab_df.to_csv(
#     "vocabulary_review.csv",
#     index=False,
#     encoding="utf-8-sig"
# )

In [31]:
def normalize_text(text):
    words = text.split()

    normalized_words = []
    changes = 0

    for word in words:

        # Never normalize protected words
        if word in protected_words:
            normalized_words.append(word)
            continue

        new_word = slang_dict.get(word, word)

        if new_word != word:
            changes += 1

        normalized_words.append(new_word)

    return " ".join(normalized_words), changes

In [32]:
result = df["cleaned"].apply(normalize_text)

df["normalized"] = result.str[0]
df["normalization_changes"] = result.str[1]

print(f"Reviews normalized : {(df['normalization_changes']>0).sum():,}")

print()

print(df["normalization_changes"].describe())

Reviews normalized : 131,338

count    193827.00000
mean          2.12668
std           2.79557
min           0.00000
25%           0.00000
50%           1.00000
75%           3.00000
max          47.00000
Name: normalization_changes, dtype: float64

In [33]:
changed_reviews = df[
    df["normalization_changes"] > 0
][[
    "cleaned",
    "normalized",
    "normalization_changes"
]]

changed_reviews.head(20)

,cleaned,normalized,normalization_changes
0,ribet banget ni apk sumpah dikir verif dikit verif udhmah nyedot pulsa mulu tolong benerin lah jangan ribet gini mau pake aja ribet cuh,ribet banget nih apk sumpah dikir verif dikit verif udhmah nyedot pulsa mulu tolong benerin lah jangan ribet begini mau pakai saja ribet cuh,4
1,kenapa qris ga bisa di pakai ya daritadi loading mulu transfer uang juga gabisa,kenapa qris enggak bisa di pakai ya daritadi loading mulu transfer uang juga enggak bisa,2
2,aplikasi nya sampah kenapa tiba tiba keluar terus registrasi ulang lagi harus pake sms pulsa pula sangat tidak membantu delete,aplikasi nya sampah kenapa tiba tiba keluar terus registrasi ulang lagi harus pakai sms pulsa pula sangat tidak membantu delete,1
5,masa gue setiap isi flazz selalu gagal tapi kedebit gak layak bgt gue ini transaksi ke 4 gue,masa gue setiap isi flazz selalu gagal tapi kedebit enggak layak banget gue ini transaksi ke 4 gue,2
7,sinyal penuh internet lancar tapi masih aj kode merah aneh bener,sinyal penuh internet lancar tapi masih saja kode merah aneh benar,2
11,kenapa setelah masuk ke mbanking harus aktivasi ulang ke cs buat transaksi finansialnya padahal sebelumnya pernah aktif di hp yg sama ribet banget tau gak sih,kenapa setelah masuk ke mbanking harus aktivasi ulang ke cs buat transaksi finansialnya padahal sebelumnya pernah aktif di hp yang sama ribet banget tau enggak sih,2
12,kasik bintang 1 dulu aku new user bca saldoku 96k pas di cek lagi kok berkurang jadi 71k ya terus notif transaksi jga lambat gaada catatan transaksi jga tolong dong di perbaiki kalau udh dibalas nanti aku tambahin 1 bintang lagi,kasik bintang 1 dulu aku new user bca saldoku 96k pas di cek lagi kok berkurang jadi 71k ya terus notif transaksi juga lambat enggak ada catatan transaksi juga tolong dong di perbaiki kalau sudah dibalas nanti aku tambahkan 1 bintang lagi,5
13,ini bca lgi gangguan apa gimana saya loading terus mau masuk ke bca mobile,ini bca lagi gangguan apa bagaimana saya loading terus mau masuk ke bca mobile,2
14,tiap verifikasi wajah knapa slalu gagal ganti hp karna hp lama udah eror malah pas mau log in ke bca susah bgt tiap verifikasi gagal terus padahal pencahayaan udah aman tolong bantuan dan sarqnnya dong,tiap verifikasi wajah knapa selalu gagal ganti hp karena hp lama sudah eror malah pas mau log ini ke bca susah banget tiap verifikasi gagal terus padahal pencahayaan sudah aman tolong bantuan dan sarqnnya dong,6
15,setelah d update malah minta masukin norek seperti awal install bca trus ga bs d ceklist buat lanjutin k proses selanjutnya ini gmn sih sistemnya bukannya memudahkan tp malah menyulitkan padahal sy sll menggunakan bca dlm setiap transaksi,setelah di update malah meminta memasuki norek seperti awal install bca terus enggak bisa di ceklis buat lanjutkan ke proses selanjutnya ini bagaimana sih sistemnya bukannya memudahkan tapi malah menyulitkan padahal saya selalu menggunakan bca dalam setiap transaksi,15
16,bca gaje sinyal bagus tapi merah mulu,bca enggak jelas sinyal bagus tapi merah mulu,1
17,apa ini aplikasi bintang 1 register mobile banking dari pagi ampe sore bilangnya tunggu indikator hijau pdahal tidak ada indikator sama sekali ampe habis pulsa gue 20k,apa ini aplikasi bintang 1 register mobile banking dari pagi sampai sore bilangnya tunggu indikator hijau padahal tidak ada indikator sama sekali sampai habis pulsa gue 20k,3
18,akun nya ga bis akembali,akun nya enggak bis akembali,1
20,indikator lampu merah terus mana sering gitu mulu lagi setiap mau dipakek kayak gitu mulu sampai berjam2 pada hak sinyal bagus apk udah diperbarui kejadian terus berulang2 dan sering,indikator lampu merah terus mana sering begitu mulu lagi setiap mau dipakek kayak begitu mulu sampai berjam2 pada hak sinyal bagus apk sudah diperbarui kejadian terus berulang2 dan sering,3
21,kenapa yaa tiap mau buat m bca selalu stuck di pembuatan sandi m bca pas klik send tunggu lampu indikator hijau tapi letak indikator lampunya ga ada udh coba install uninstall restart hp ttp ga mau jaringan wifi sama data juga oke ga ada kendala ulang2 trus smpai brp kali isi pulsa pdhl dri dulu suka bgt pake ni aplikasi krna simpel ini ke reset karna ganti no hp tolong dongg solusinya,kenapa ya tiap mau buat sama bca selalu stuck di pembuatan sandi sama bca pas klik send tunggu lampu indikator hijau tapi letak indikator lampunya enggak ada sudah coba install uninstall restart hp tetap enggak mau jaringan wifi sama data juga oke enggak ada kendala ulang2 terus sampai berapa kali isi pulsa padahal dari dulu suka banget pakai nih aplikasi karena simpel ini ke reset karena ganti no hp tolong dong solusinya,19
23,terlalu banyak error kirain ada update an lagi ternyata tidak,terlalu banyak error mengira ada update an lagi ternyata tidak,1
24,kenapa dari kemarin nggak bisa login apa sedang gangguan kah,kenapa dari kemarin enggak bisa login apa sedang gangguan kah,1
26,payah jauh sama livin mandiri saat kirim sms kode tapi gak masuk masuk hanya muter aja,payah jauh sama livin mandiri saat kirim sms kode tapi enggak masuk masuk hanya muter saja,2
27,qris bca sekarang lemot bgt,qris bca sekarang lemot banget,1
28,semenjak di update jadi lama bgt kalau mau masuk mbanking nya mau bayar2 pake qris juga jadi males,semenjak di update jadi lama banget kalau mau masuk mbanking nya mau bayar2 pakai qris juga jadi malas,3

Reduce three or more consecutive identical characters  
example = "paraaahhhhhh" , "jeeelleeekkkk"

In [34]:
def normalize_repeated_chars(text):
    # Reduce 3 or more repeated characters to a single character
    return re.sub(r"(.)\1{2,}", r"\1", text)

df["final_text"] = (
    df["normalized"]
    .apply(normalize_repeated_chars)
)

In [35]:
repeat_changed = df[
    df["normalized"] != df["final_text"]
][[
    "normalized",
    "final_text"
]]

print(f"Rows affected : {len(repeat_changed):,}")

repeat_changed.head(20)

Rows affected : 9,848

,normalized,final_text
19,makin paraaaaaah setelah diupdate aplikasi nya ya allah,makin parah setelah diupdate aplikasi nya ya allah
64,apk baru diupdate malah enggak bisa dibuka kan aneh apk ngennn,apk baru diupdate malah enggak bisa dibuka kan aneh apk ngen
101,kinerja bank nya bagus aplilkasi nya lemot kalau buka qris diperbaiki yang komplain sudah banyak kok masih bilang enggak ada kendala haduhhhh mau jadi bank bumn enggak mau terima kritik 24 12 sudah berapa minggu enggak ada perbaikan qris mu itu mu pecat saja,kinerja bank nya bagus aplilkasi nya lemot kalau buka qris diperbaiki yang komplain sudah banyak kok masih bilang enggak ada kendala haduh mau jadi bank bumn enggak mau terima kritik 24 12 sudah berapa minggu enggak ada perbaikan qris mu itu mu pecat saja
102,jangan terlalu percaya dengan aplikasi saat urgen lampu indikatornya merah terussss kan goblog,jangan terlalu percaya dengan aplikasi saat urgen lampu indikatornya merah terus kan goblog
161,ini bagaimana sih bca tolong dong yang jelas masa potongan bulanan potongnnya enggak jls benar bulan kemarin saldo saya di sedot 25000 sekarang malah 24000 tapi di prosedurnya potongan setiap bulan hanya 15000 bagaimana ini bca aneh,ini bagaimana sih bca tolong dong yang jelas masa potongan bulanan potongnnya enggak jls benar bulan kemarin saldo saya di sedot 250 sekarang malah 240 tapi di prosedurnya potongan setiap bulan hanya 150 bagaimana ini bca aneh
162,ih paling kesel sama bca indikator merah tusss lama lagi ayok di perbaiki padahal sinyal bagus kebiasaan setiap mau pembayaran merah teusss lamaaa lagi,ih paling kesel sama bca indikator merah tus lama lagi ayok di perbaiki padahal sinyal bagus kebiasaan setiap mau pembayaran merah teus lama lagi
168,bca sebagai bank no 1 di indonesia ternyata tidak bisa memberi penjelasan kemana hilangnya uang saya yang tidak tercantum dalam mutasi memang nominalnya hanya 30 000 tapi itu jelas membuktikan keteledoran pihak bca dalam menjaga uang nasabahnya bagaimana jika 30 000 dikalikan ribuan orang lain yang enggak sadar uangnya terpotong enggak jelas tolong bca jelaskan kemana uang saya itu,bca sebagai bank no 1 di indonesia ternyata tidak bisa memberi penjelasan kemana hilangnya uang saya yang tidak tercantum dalam mutasi memang nominalnya hanya 30 0 tapi itu jelas membuktikan keteledoran pihak bca dalam menjaga uang nasabahnya bagaimana jika 30 0 dikalikan ribuan orang lain yang enggak sadar uangnya terpotong enggak jelas tolong bca jelaskan kemana uang saya itu
186,ini kenapa ya setiap mau masuk apk selalu ada tulisan 205 transaksi tidak dapat diproses coba lagi nanti kenapaaaaa saya mau cek saldo mau transfer padahal sinyal bagus sudah beberapa kali restart hp tolong diperbaiki secepatnya,ini kenapa ya setiap mau masuk apk selalu ada tulisan 205 transaksi tidak dapat diproses coba lagi nanti kenapa saya mau cek saldo mau transfer padahal sinyal bagus sudah beberapa kali restart hp tolong diperbaiki secepatnya
217,wahaii pemuda bikin aplikasi publik yang benerlah tiap buka aplikasi meminta verifikasi sms mulu lagi bikin kuis jari jariiiii lu meminta sms terus,wahaii pemuda bikin aplikasi publik yang benerlah tiap buka aplikasi meminta verifikasi sms mulu lagi bikin kuis jari jari lu meminta sms terus
227,seusai di update jadi leeeemoootttt,seusai di update jadi lemot
275,semakin kesini makin buruk buka kamera qris lama banget beli token listrik gagal terus gimaaana sih bca,semakin kesini makin buruk buka kamera qris lama banget beli token listrik gagal terus gimana sih bca
283,parah crush mulu woy ganggu banget ini pekerjaan delay muluuuu,parah crush mulu woy ganggu banget ini pekerjaan delay mulu
286,sering laggg error enggak bisa transfer ke rekening lain,sering lag error enggak bisa transfer ke rekening lain
289,bca mengecewakan banget setelah diperbarui selama 2 bulan terakhir bca ku jadi error terus mana posisi mau bayar sudah sampai telepon ke operator katanya tidak ada kendala dipastikan jangan berkurang jaringan nya lah dll padahal jaringan fulll pakai data juga tapi malah tulisan something went wrong terus sumpah sih baru kali ini kecewa sama bca yang padahal enggak pernah bermasalah sebelum nya,bca mengecewakan banget setelah diperbarui selama 2 bulan terakhir bca ku jadi error terus mana posisi mau bayar sudah sampai telepon ke operator katanya tidak ada kendala dipastikan jangan berkurang jaringan nya lah dll padahal jaringan ful pakai data juga tapi malah tulisan something went wrong terus sumpah sih baru kali ini kecewa sama bca yang padahal enggak pernah bermasalah sebelum nya
297,bikin emosi kalau lagi mbangking makin kesini susah banget masuk gue lagi di desa susah cari atm woiiiii,bikin emosi kalau lagi mbangking makin kesini susah banget masuk gue lagi di desa susah cari atm woi
306,sejak up grade versi baru jadi lambat lemot lebih mengecewakan lagi sekarang hapus inbox maximal 5 padahal kita ada 4000an inbox dulu bisa sekali hapus semua,sejak up grade versi baru jadi lambat lemot lebih mengecewakan lagi sekarang hapus inbox maximal 5 padahal kita ada 40an inbox dulu bisa sekali hapus semua
320,saya mbca lovers tapi sekarang makin lemot indikatornya merah mulu lemotttt mau transaksi qris transfer jadi lamaa jadi bikin kesal enggak nyaman habis di jebol ya upgrade antivirus enakan sama banking bank sebelah cepat kalau sudah normal saya rubah bintang nya ke lima 5,saya mbca lovers tapi sekarang makin lemot indikatornya merah mulu lemot mau transaksi qris transfer jadi lamaa jadi bikin kesal enggak nyaman habis di jebol ya upgrade antivirus enakan sama banking bank sebelah cepat kalau sudah normal saya rubah bintang nya ke lima 5
346,bca lemottt najisss sudah lemot sering gangguan payahhh,bca lemot najis sudah lemot sering gangguan payah
372,diupdate tambah abooott alias lemot paraaahh,diupdate tambah abott alias lemot parahh
374,buruk banget saya sudah ganti hp dan enggak bisa masuk karena verivikasi gagal teruuuuus mohon perbaikannyaaaaaa buruuuuk sekali,buruk banget saya sudah ganti hp dan enggak bisa masuk karena verivikasi gagal terus mohon perbaikannya buruk sekali

In [36]:
final_dataset = df[
    [
        "reviewId",
        "bank",
        "score",
        "year",
        "final_text"
    ]
].copy()

final_dataset.rename(
    columns={
        "final_text": "text"
    },
    inplace=True
)

final_dataset.head(30)

,reviewId,bank,score,year,text
0,e17751da-bf2e-4a8f-a5a8-334206bb93ca,BCAMOBILE_REVIEWS,1,2025,ribet banget nih apk sumpah dikir verif dikit verif udhmah nyedot pulsa mulu tolong benerin lah jangan ribet begini mau pakai saja ribet cuh
1,3481f1d1-a22f-445f-ae2f-ed8c2c9dca53,BCAMOBILE_REVIEWS,2,2025,kenapa qris enggak bisa di pakai ya daritadi loading mulu transfer uang juga enggak bisa
2,af69ec6d-cc97-404e-b86a-e5f5b5f1f711,BCAMOBILE_REVIEWS,1,2025,aplikasi nya sampah kenapa tiba tiba keluar terus registrasi ulang lagi harus pakai sms pulsa pula sangat tidak membantu delete
3,32d28ac6-c538-4749-969f-8af060915d96,BCAMOBILE_REVIEWS,3,2025,bagus
4,f99259b7-0d45-4422-b667-6c4fd521638b,BCAMOBILE_REVIEWS,1,2025,tidak ada solusi ketika ada kendala di persulit di lempar kesana kesini sangat mengecewakan harusnya respon dan solusi yang di berikan
5,1b50a316-798a-42a3-8bfe-0154853d0f4a,BCAMOBILE_REVIEWS,1,2025,masa gue setiap isi flazz selalu gagal tapi kedebit enggak layak banget gue ini transaksi ke 4 gue
6,6ac413fd-0745-430c-b545-da39c54ff60e,BCAMOBILE_REVIEWS,1,2025,mau aktifasi di handphone baru semakin ribet dan sulit tidak seperti yang lalu
7,8fce3e87-d488-4ed5-9f91-17cdae1a6b5f,BCAMOBILE_REVIEWS,1,2025,sinyal penuh internet lancar tapi masih saja kode merah aneh benar
8,b8568501-8111-48cc-9fd9-eefda3fdd1d6,BCAMOBILE_REVIEWS,2,2025,sinyal bagus tetap biru terus membuat lama pembayaran
9,06df10c9-69d4-4589-bd3d-505443d4fd53,BCAMOBILE_REVIEWS,1,2025,saya mau login menggunakan pulsa kode selalu tidak keluar
10,7cdf7f58-769d-4779-87f6-a0184e893fac,BCAMOBILE_REVIEWS,1,2025,kenapa aplikasi ini sering sekarat
11,d5d74905-2ace-40d0-a412-f43373336eff,BCAMOBILE_REVIEWS,2,2025,kenapa setelah masuk ke mbanking harus aktivasi ulang ke cs buat transaksi finansialnya padahal sebelumnya pernah aktif di hp yang sama ribet banget tau enggak sih
12,4ce97c61-d21c-478f-8bef-80580e4c828e,BCAMOBILE_REVIEWS,1,2025,kasik bintang 1 dulu aku new user bca saldoku 96k pas di cek lagi kok berkurang jadi 71k ya terus notif transaksi juga lambat enggak ada catatan transaksi juga tolong dong di perbaiki kalau sudah dibalas nanti aku tambahkan 1 bintang lagi
13,b7700811-d205-4b12-94fa-db9a02266059,BCAMOBILE_REVIEWS,2,2025,ini bca lagi gangguan apa bagaimana saya loading terus mau masuk ke bca mobile
14,3435926c-50fa-4b27-93ee-8112bb2d53c9,BCAMOBILE_REVIEWS,2,2025,tiap verifikasi wajah knapa selalu gagal ganti hp karena hp lama sudah eror malah pas mau log ini ke bca susah banget tiap verifikasi gagal terus padahal pencahayaan sudah aman tolong bantuan dan sarqnnya dong
15,84fad0c6-980e-4263-843c-2d444e80799d,BCAMOBILE_REVIEWS,1,2025,setelah di update malah meminta memasuki norek seperti awal install bca terus enggak bisa di ceklis buat lanjutkan ke proses selanjutnya ini bagaimana sih sistemnya bukannya memudahkan tapi malah menyulitkan padahal saya selalu menggunakan bca dalam setiap transaksi
16,46a9b775-12db-4cad-a259-83bdd6ff5b78,BCAMOBILE_REVIEWS,1,2025,bca enggak jelas sinyal bagus tapi merah mulu
17,fb449431-50de-41a5-9809-df47d670ee2a,BCAMOBILE_REVIEWS,1,2025,apa ini aplikasi bintang 1 register mobile banking dari pagi sampai sore bilangnya tunggu indikator hijau padahal tidak ada indikator sama sekali sampai habis pulsa gue 20k
18,1390039e-cd94-4046-b864-523acc647bc9,BCAMOBILE_REVIEWS,1,2025,akun nya enggak bis akembali
19,5fa82eb0-e111-4a8f-b397-8a6fd37d1709,BCAMOBILE_REVIEWS,1,2025,makin parah setelah diupdate aplikasi nya ya allah
20,6881a68b-b85e-4ba0-9d8b-d5a2c21a6ca4,BCAMOBILE_REVIEWS,1,2025,indikator lampu merah terus mana sering begitu mulu lagi setiap mau dipakek kayak begitu mulu sampai berjam2 pada hak sinyal bagus apk sudah diperbarui kejadian terus berulang2 dan sering
21,d00b4bb9-41b6-438f-9a06-699a2aded5ff,BCAMOBILE_REVIEWS,2,2025,kenapa ya tiap mau buat sama bca selalu stuck di pembuatan sandi sama bca pas klik send tunggu lampu indikator hijau tapi letak indikator lampunya enggak ada sudah coba install uninstall restart hp tetap enggak mau jaringan wifi sama data juga oke enggak ada kendala ulang2 terus sampai berapa kali isi pulsa padahal dari dulu suka banget pakai nih aplikasi karena simpel ini ke reset karena ganti no hp tolong dong solusinya
22,7b37ce96-75c9-4854-8ee8-0a96299030a4,BCAMOBILE_REVIEWS,2,2025,indikator merah mulu setelah update
23,12880faf-c8a8-48ba-a35e-49d5ed40f677,BCAMOBILE_REVIEWS,1,2025,terlalu banyak error mengira ada update an lagi ternyata tidak
24,e62ba293-ed78-4fc3-b6b4-edb67d92bc02,BCAMOBILE_REVIEWS,3,2025,kenapa dari kemarin enggak bisa login apa sedang gangguan kah
25,a60449ad-d073-4537-af5c-77d70c859130,BCAMOBILE_REVIEWS,1,2025,sampah
26,cfe338ae-ef40-4f19-9c40-5af0ce2de930,BCAMOBILE_REVIEWS,1,2025,payah jauh sama livin mandiri saat kirim sms kode tapi enggak masuk masuk hanya muter saja
27,dd6c83ca-191b-4d28-929f-fdb82bfbc8e3,BCAMOBILE_REVIEWS,1,2025,qris bca sekarang lemot banget
28,1abacd2c-5fe9-40fc-8141-fc2b87e585c9,BCAMOBILE_REVIEWS,2,2025,semenjak di update jadi lama banget kalau mau masuk mbanking nya mau bayar2 pakai qris juga jadi malas
29,ac826b99-4cee-4aac-afc3-fe502ad86288,BCAMOBILE_REVIEWS,1,2025,buka qris kenapa loading mulu sih

In [38]:
final_dataset.shape

(193827, 5)

In [39]:
final_dataset.to_csv("data/preprocessed_data.csv", index=False)