In [8]:
import pandas as pd
import numpy as np

In [9]:
DATA_PATH = '../data/combined_dataset.csv'

df = pd.read_csv(DATA_PATH)

print(df.shape)

df.head()

(85008, 12)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank
0,ce39a363-2cc3-47bc-b08f-eed5aaf1bd5a,Frandika Bule,https://play-lh.googleusercontent.com/a/ACg8oc...,Versi 4.5.5 tidak bisa dibuka,1,0,4.5.5,2025-01-02 17:09:03,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2025-01-02 18:29:10,4.5.5,BCAMOBILE_REVIEWS
1,78e922fb-9073-493b-957e-c4a05a0bf671,muhammad farhan,https://play-lh.googleusercontent.com/a-/ALV-U...,Kenapa tiba² force close di S10+ Setelah di up...,2,0,4.5.0,2024-10-23 00:07:27,Silakan mencoba secara berkala untuk menonakti...,2024-10-23 18:00:22,4.5.0,BCAMOBILE_REVIEWS
2,58d354f8-f49e-4323-adf9-13e7248bebd5,Wildan Herdiansyah,https://play-lh.googleusercontent.com/a-/ALV-U...,BANK KONYOL,1,0,NaN,2023-11-07 17:58:47,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2023-11-07 18:55:47,NaN,BCAMOBILE_REVIEWS
3,39b5b0dd-4b4e-4705-9ca5-1a2744f7bec0,Imam Anjasmara,https://play-lh.googleusercontent.com/a-/ALV-U...,Dari tanggal 14 kemarin apk bca Mobile nya gk ...,1,4,4.7.4,2025-10-16 21:24:49,Sangat disayangkan atas kendala yang terjadi. ...,2025-10-16 22:06:33,4.7.4,BCAMOBILE_REVIEWS
4,dd53feb8-f857-462d-8d7b-3fb518bfd5c0,Deri Kancil,https://play-lh.googleusercontent.com/a-/ALV-U...,Kenapa sih kaya tiap bulan itu sering banget g...,1,0,NaN,2024-04-25 10:53:16,Mohon maaf atas ketidaknyamanannya. Ulasan Bap...,2024-04-25 11:45:19,NaN,BCAMOBILE_REVIEWS

In [10]:
df.isnull().sum().sort_values(ascending=False)

appVersion              17527
reviewCreatedVersion    17527
repliedAt                 653
replyContent              653
content                     0
userImage                   0
userName                    0
reviewId                    0
at                          0
thumbsUpCount               0
score                       0
bank                        0
dtype: int64

In [11]:
print("Duplicate Rows :", df.duplicated().sum())
print("Duplicate reviewId :", df["reviewId"].duplicated().sum())
print("Duplicate Content :", df["content"].duplicated().sum())

Duplicate Rows : 0
Duplicate reviewId : 0
Duplicate Content : 2886

In [12]:
df.dtypes

reviewId                object
userName                object
userImage               object
content                 object
score                    int64
thumbsUpCount            int64
reviewCreatedVersion    object
at                      object
replyContent            object
repliedAt               object
appVersion              object
bank                    object
dtype: object

dropping unnecessary columns

In [13]:
columns_to_drop = [
  "userImage",
  "userName",
  "replyContent",
  "repliedAt",
  "appVersion",
  "reviewCreatedVersion"
]

df = df.drop(columns=columns_to_drop)

df.head()

,reviewId,content,score,thumbsUpCount,at,bank
0,ce39a363-2cc3-47bc-b08f-eed5aaf1bd5a,Versi 4.5.5 tidak bisa dibuka,1,0,2025-01-02 17:09:03,BCAMOBILE_REVIEWS
1,78e922fb-9073-493b-957e-c4a05a0bf671,Kenapa tiba² force close di S10+ Setelah di up...,2,0,2024-10-23 00:07:27,BCAMOBILE_REVIEWS
2,58d354f8-f49e-4323-adf9-13e7248bebd5,BANK KONYOL,1,0,2023-11-07 17:58:47,BCAMOBILE_REVIEWS
3,39b5b0dd-4b4e-4705-9ca5-1a2744f7bec0,Dari tanggal 14 kemarin apk bca Mobile nya gk ...,1,4,2025-10-16 21:24:49,BCAMOBILE_REVIEWS
4,dd53feb8-f857-462d-8d7b-3fb518bfd5c0,Kenapa sih kaya tiap bulan itu sering banget g...,1,0,2024-04-25 10:53:16,BCAMOBILE_REVIEWS

checking missing values

In [14]:
df.isnull().sum().sort_values(ascending=False)

reviewId         0
content          0
score            0
thumbsUpCount    0
at               0
bank             0
dtype: int64

duplicate check

In [15]:
print("Duplicate Rows :", df.duplicated().sum())
print("Duplicate reviewId :", df["reviewId"].duplicated().sum())
print("Duplicate Content :", df["content"].duplicated().sum())

Duplicate Rows : 0
Duplicate reviewId : 0
Duplicate Content : 2886

converting "at" column

In [16]:
df["at"] = pd.to_datetime(df["at"])

df["at"].head()

0   2025-01-02 17:09:03
1   2024-10-23 00:07:27
2   2023-11-07 17:58:47
3   2025-10-16 21:24:49
4   2024-04-25 10:53:16
Name: at, dtype: datetime64[ns]

In [17]:
print(df.shape)

df.sample(5)

(85008, 6)

,reviewId,content,score,thumbsUpCount,at,bank
29822,82e5aa46-bb4c-443b-9fbc-5e21892b35e9,Brimo memang mantaap,1,1,2024-11-05 14:15:00,BRIMO_REVIEWS
73517,478a5301-d388-4439-9e87-b0d55ea26010,Harus di perbaharui lagi gak maksimal,1,0,2024-07-15 13:19:12,WONDR_BNI_REVIEWS
72116,8c287495-da0b-42cc-a532-fb6e1c8903ce,Topup e money terbatas,1,0,2025-08-03 16:09:20,WONDR_BNI_REVIEWS
65068,922b5eef-1d1e-4fe2-8573-0141b2878695,kenapa saya login gak bisa tulisan update teru...,1,0,2025-11-07 22:35:32,WONDR_BNI_REVIEWS
50515,ee76aa5f-5285-4020-9032-67dc543f8e64,"transaksi tidak berhasil, mohon tunggu beberap...",1,0,2024-09-12 01:50:57,LIVIN_MANDIRI_REVIEWS

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85008 entries, 0 to 85007
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   reviewId       85008 non-null  object
 1   content        85008 non-null  object
 2   score          85008 non-null  int64
 3   thumbsUpCount  85008 non-null  int64
 4   at             85008 non-null  datetime64[ns]
 5   bank           85008 non-null  object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 3.9+ MB

exporting

In [22]:
df.to_csv(
    "cleaned_dataset.csv",
    index=False
)